/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:53:01 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/swift/libswiftAppleArchive.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtCC12AppleArchive17ArchiveByteStreamP33_DB3D9388F2DA7AF4C55DCA57DFCC6AC722CustomByteStreamBridge : _UKNOWN_SUPERCLASS_ {

	 instance;
	 aaStream;

}
@end

