/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:01 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libboringssl.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/OS_boringssl_psk_cache.h>

@protocol OS_sec_array, OS_dispatch_queue;
@class NSObject, boringssl_concrete_boringssl_ctx, NSString;

@interface boringssl_concrete_boringssl_psk_cache : NSObject <OS_boringssl_psk_cache> {

	NSObject*<OS_sec_array> list;
	boringssl_concrete_boringssl_ctx* context;
	/*^block*/id psk_selection_block;
	NSObject*<OS_dispatch_queue> psk_selection_queue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@end

