/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:53:01 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfstorage.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSObject, NSString;

@interface AppletEntity : NSManagedObject

@property (nonatomic,retain) NSObject * applets; 
@property (assign,nonatomic) long long crsUpdateCounter; 
@property (nonatomic,copy) NSString * seid; 
@property (assign,nonatomic) long long version; 
+(id)fetchRequest;
@end

