/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:53:01 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfstorage.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfstorage.dylib/NFStorageController.h>

@interface NFStorageControllerApplet : NFStorageController
-(id)name;
-(id)_deleteAllAppletEntities;
-(id)dbProtectionType;
-(id)fetchAppletEntitiesWithError:(id*)arg1 ;
-(id)updateAppletEntitiesWithConfig:(id)arg1 ;
-(void)deleteAllAppletEntities;
@end

