/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDNFCVersions : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _hardwareType;
	unsigned _middlewareVersion;
	unsigned _nfccFWRevision;
	unsigned _nfccFWVersion;
	unsigned _nfccHWVersion;
	unsigned _nfccROMVersion;
	NSString* _platformVersion;
	unsigned _seAvailableIndices;
	unsigned _seDeviceType;
	unsigned _seFWVersion;
	unsigned _seHWVersion;
	unsigned _seMigrationInst;
	unsigned _seMigrationPkgs;
	unsigned _seMigrationState;
	unsigned _seOSMode;
	unsigned _seReferenceCounter;
	unsigned _seRestrictedMode;
	unsigned _seSequenceCounter;
	unsigned _seSignKeyType;
	unsigned _seTotalIndices;
	unsigned _seTransientDeselect;
	unsigned _seTransientPersistent;
	unsigned _seTransientReset;
	unsigned _seosHWVersion;
	unsigned _seosMigrationState;
	unsigned _seosOSMode;
	unsigned _seosOSVersion;
	NSString* _seosPlatformID;
	unsigned _seosSignKeyType;
	unsigned _seosTransientDeselect;
	unsigned _seosTransientPersistent;
	unsigned _seosTransientReset;
	SCD_Struct_AW14 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                  //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) char hasMiddlewareVersion; 
@property (assign,nonatomic) unsigned middlewareVersion;                    //@synthesize middlewareVersion=_middlewareVersion - In the implementation block
@property (nonatomic,readonly) char hasPlatformVersion; 
@property (nonatomic,retain) NSString * platformVersion;                    //@synthesize platformVersion=_platformVersion - In the implementation block
@property (assign,nonatomic) char hasNfccHWVersion; 
@property (assign,nonatomic) unsigned nfccHWVersion;                        //@synthesize nfccHWVersion=_nfccHWVersion - In the implementation block
@property (assign,nonatomic) char hasNfccROMVersion; 
@property (assign,nonatomic) unsigned nfccROMVersion;                       //@synthesize nfccROMVersion=_nfccROMVersion - In the implementation block
@property (assign,nonatomic) char hasNfccFWVersion; 
@property (assign,nonatomic) unsigned nfccFWVersion;                        //@synthesize nfccFWVersion=_nfccFWVersion - In the implementation block
@property (assign,nonatomic) char hasNfccFWRevision; 
@property (assign,nonatomic) unsigned nfccFWRevision;                       //@synthesize nfccFWRevision=_nfccFWRevision - In the implementation block
@property (assign,nonatomic) char hasSeDeviceType; 
@property (assign,nonatomic) unsigned seDeviceType;                         //@synthesize seDeviceType=_seDeviceType - In the implementation block
@property (assign,nonatomic) char hasSeHWVersion; 
@property (assign,nonatomic) unsigned seHWVersion;                          //@synthesize seHWVersion=_seHWVersion - In the implementation block
@property (assign,nonatomic) char hasSeFWVersion; 
@property (assign,nonatomic) unsigned seFWVersion;                          //@synthesize seFWVersion=_seFWVersion - In the implementation block
@property (assign,nonatomic) char hasSeSignKeyType; 
@property (assign,nonatomic) unsigned seSignKeyType;                        //@synthesize seSignKeyType=_seSignKeyType - In the implementation block
@property (assign,nonatomic) char hasSeSequenceCounter; 
@property (assign,nonatomic) unsigned seSequenceCounter;                    //@synthesize seSequenceCounter=_seSequenceCounter - In the implementation block
@property (assign,nonatomic) char hasSeReferenceCounter; 
@property (assign,nonatomic) unsigned seReferenceCounter;                   //@synthesize seReferenceCounter=_seReferenceCounter - In the implementation block
@property (assign,nonatomic) char hasSeOSMode; 
@property (assign,nonatomic) unsigned seOSMode;                             //@synthesize seOSMode=_seOSMode - In the implementation block
@property (assign,nonatomic) char hasSeRestrictedMode; 
@property (assign,nonatomic) unsigned seRestrictedMode;                     //@synthesize seRestrictedMode=_seRestrictedMode - In the implementation block
@property (assign,nonatomic) char hasSeMigrationState; 
@property (assign,nonatomic) unsigned seMigrationState;                     //@synthesize seMigrationState=_seMigrationState - In the implementation block
@property (assign,nonatomic) char hasSeMigrationPkgs; 
@property (assign,nonatomic) unsigned seMigrationPkgs;                      //@synthesize seMigrationPkgs=_seMigrationPkgs - In the implementation block
@property (assign,nonatomic) char hasSeMigrationInst; 
@property (assign,nonatomic) unsigned seMigrationInst;                      //@synthesize seMigrationInst=_seMigrationInst - In the implementation block
@property (nonatomic,readonly) char hasSeosPlatformID; 
@property (nonatomic,retain) NSString * seosPlatformID;                     //@synthesize seosPlatformID=_seosPlatformID - In the implementation block
@property (assign,nonatomic) char hasSeosHWVersion; 
@property (assign,nonatomic) unsigned seosHWVersion;                        //@synthesize seosHWVersion=_seosHWVersion - In the implementation block
@property (assign,nonatomic) char hasSeosOSVersion; 
@property (assign,nonatomic) unsigned seosOSVersion;                        //@synthesize seosOSVersion=_seosOSVersion - In the implementation block
@property (assign,nonatomic) char hasSeosOSMode; 
@property (assign,nonatomic) unsigned seosOSMode;                           //@synthesize seosOSMode=_seosOSMode - In the implementation block
@property (assign,nonatomic) char hasSeosSignKeyType; 
@property (assign,nonatomic) unsigned seosSignKeyType;                      //@synthesize seosSignKeyType=_seosSignKeyType - In the implementation block
@property (assign,nonatomic) char hasSeosMigrationState; 
@property (assign,nonatomic) unsigned seosMigrationState;                   //@synthesize seosMigrationState=_seosMigrationState - In the implementation block
@property (assign,nonatomic) char hasHardwareType; 
@property (assign,nonatomic) unsigned hardwareType;                         //@synthesize hardwareType=_hardwareType - In the implementation block
@property (assign,nonatomic) char hasSeTransientDeselect; 
@property (assign,nonatomic) unsigned seTransientDeselect;                  //@synthesize seTransientDeselect=_seTransientDeselect - In the implementation block
@property (assign,nonatomic) char hasSeTransientReset; 
@property (assign,nonatomic) unsigned seTransientReset;                     //@synthesize seTransientReset=_seTransientReset - In the implementation block
@property (assign,nonatomic) char hasSeTransientPersistent; 
@property (assign,nonatomic) unsigned seTransientPersistent;                //@synthesize seTransientPersistent=_seTransientPersistent - In the implementation block
@property (assign,nonatomic) char hasSeAvailableIndices; 
@property (assign,nonatomic) unsigned seAvailableIndices;                   //@synthesize seAvailableIndices=_seAvailableIndices - In the implementation block
@property (assign,nonatomic) char hasSeTotalIndices; 
@property (assign,nonatomic) unsigned seTotalIndices;                       //@synthesize seTotalIndices=_seTotalIndices - In the implementation block
@property (assign,nonatomic) char hasSeosTransientDeselect; 
@property (assign,nonatomic) unsigned seosTransientDeselect;                //@synthesize seosTransientDeselect=_seosTransientDeselect - In the implementation block
@property (assign,nonatomic) char hasSeosTransientReset; 
@property (assign,nonatomic) unsigned seosTransientReset;                   //@synthesize seosTransientReset=_seosTransientReset - In the implementation block
@property (assign,nonatomic) char hasSeosTransientPersistent; 
@property (assign,nonatomic) unsigned seosTransientPersistent;              //@synthesize seosTransientPersistent=_seosTransientPersistent - In the implementation block
-(void)setSeosPlatformID:(NSString *)arg1 ;
-(void)setMiddlewareVersion:(unsigned)arg1 ;
-(void)setHasMiddlewareVersion:(char)arg1 ;
-(char)hasMiddlewareVersion;
-(char)hasPlatformVersion;
-(void)setNfccHWVersion:(unsigned)arg1 ;
-(void)setHasNfccHWVersion:(char)arg1 ;
-(char)hasNfccHWVersion;
-(void)setNfccROMVersion:(unsigned)arg1 ;
-(void)setHasNfccROMVersion:(char)arg1 ;
-(char)hasNfccROMVersion;
-(void)setNfccFWVersion:(unsigned)arg1 ;
-(void)setHasNfccFWVersion:(char)arg1 ;
-(char)hasNfccFWVersion;
-(void)setNfccFWRevision:(unsigned)arg1 ;
-(void)setHasNfccFWRevision:(char)arg1 ;
-(char)hasNfccFWRevision;
-(void)setSeDeviceType:(unsigned)arg1 ;
-(void)setHasSeDeviceType:(char)arg1 ;
-(char)hasSeDeviceType;
-(void)setSeHWVersion:(unsigned)arg1 ;
-(void)setHasSeHWVersion:(char)arg1 ;
-(char)hasSeHWVersion;
-(void)setSeFWVersion:(unsigned)arg1 ;
-(void)setHasSeFWVersion:(char)arg1 ;
-(char)hasSeFWVersion;
-(void)setSeSignKeyType:(unsigned)arg1 ;
-(void)setHasSeSignKeyType:(char)arg1 ;
-(char)hasSeSignKeyType;
-(void)setSeSequenceCounter:(unsigned)arg1 ;
-(void)setHasSeSequenceCounter:(char)arg1 ;
-(char)hasSeSequenceCounter;
-(void)setSeReferenceCounter:(unsigned)arg1 ;
-(void)setHasSeReferenceCounter:(char)arg1 ;
-(char)hasSeReferenceCounter;
-(void)setSeOSMode:(unsigned)arg1 ;
-(void)setHasSeOSMode:(char)arg1 ;
-(char)hasSeOSMode;
-(void)setSeRestrictedMode:(unsigned)arg1 ;
-(void)setHasSeRestrictedMode:(char)arg1 ;
-(char)hasSeRestrictedMode;
-(void)setSeMigrationState:(unsigned)arg1 ;
-(void)setHasSeMigrationState:(char)arg1 ;
-(char)hasSeMigrationState;
-(void)setSeMigrationPkgs:(unsigned)arg1 ;
-(void)setHasSeMigrationPkgs:(char)arg1 ;
-(char)hasSeMigrationPkgs;
-(void)setSeMigrationInst:(unsigned)arg1 ;
-(void)setHasSeMigrationInst:(char)arg1 ;
-(char)hasSeMigrationInst;
-(char)hasSeosPlatformID;
-(void)setSeosHWVersion:(unsigned)arg1 ;
-(void)setHasSeosHWVersion:(char)arg1 ;
-(char)hasSeosHWVersion;
-(void)setSeosOSVersion:(unsigned)arg1 ;
-(void)setHasSeosOSVersion:(char)arg1 ;
-(char)hasSeosOSVersion;
-(void)setSeosOSMode:(unsigned)arg1 ;
-(void)setHasSeosOSMode:(char)arg1 ;
-(char)hasSeosOSMode;
-(void)setSeosSignKeyType:(unsigned)arg1 ;
-(void)setHasSeosSignKeyType:(char)arg1 ;
-(char)hasSeosSignKeyType;
-(void)setSeosMigrationState:(unsigned)arg1 ;
-(void)setHasSeosMigrationState:(char)arg1 ;
-(char)hasSeosMigrationState;
-(void)setSeTransientDeselect:(unsigned)arg1 ;
-(void)setHasSeTransientDeselect:(char)arg1 ;
-(char)hasSeTransientDeselect;
-(void)setSeTransientReset:(unsigned)arg1 ;
-(void)setHasSeTransientReset:(char)arg1 ;
-(char)hasSeTransientReset;
-(void)setSeTransientPersistent:(unsigned)arg1 ;
-(void)setHasSeTransientPersistent:(char)arg1 ;
-(char)hasSeTransientPersistent;
-(void)setSeAvailableIndices:(unsigned)arg1 ;
-(void)setHasSeAvailableIndices:(char)arg1 ;
-(char)hasSeAvailableIndices;
-(void)setSeTotalIndices:(unsigned)arg1 ;
-(void)setHasSeTotalIndices:(char)arg1 ;
-(char)hasSeTotalIndices;
-(void)setSeosTransientDeselect:(unsigned)arg1 ;
-(void)setHasSeosTransientDeselect:(char)arg1 ;
-(char)hasSeosTransientDeselect;
-(void)setSeosTransientReset:(unsigned)arg1 ;
-(void)setHasSeosTransientReset:(char)arg1 ;
-(char)hasSeosTransientReset;
-(void)setSeosTransientPersistent:(unsigned)arg1 ;
-(void)setHasSeosTransientPersistent:(char)arg1 ;
-(char)hasSeosTransientPersistent;
-(unsigned)nfccHWVersion;
-(unsigned)nfccROMVersion;
-(unsigned)nfccFWVersion;
-(unsigned)nfccFWRevision;
-(unsigned)seDeviceType;
-(unsigned)seHWVersion;
-(unsigned)seFWVersion;
-(unsigned)seSignKeyType;
-(unsigned)seSequenceCounter;
-(unsigned)seReferenceCounter;
-(unsigned)seOSMode;
-(unsigned)seRestrictedMode;
-(unsigned)seMigrationState;
-(unsigned)seMigrationPkgs;
-(unsigned)seMigrationInst;
-(NSString *)seosPlatformID;
-(unsigned)seosHWVersion;
-(unsigned)seosOSVersion;
-(unsigned)seosOSMode;
-(unsigned)seosSignKeyType;
-(unsigned)seosMigrationState;
-(unsigned)seTransientDeselect;
-(unsigned)seTransientReset;
-(unsigned)seTransientPersistent;
-(unsigned)seAvailableIndices;
-(unsigned)seTotalIndices;
-(unsigned)seosTransientDeselect;
-(unsigned)seosTransientReset;
-(unsigned)seosTransientPersistent;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(NSString *)platformVersion;
-(void)setPlatformVersion:(NSString *)arg1 ;
-(void)setHasTimestamp:(char)arg1 ;
-(unsigned)middlewareVersion;
-(unsigned)hardwareType;
-(void)setHardwareType:(unsigned)arg1 ;
-(void)setHasHardwareType:(char)arg1 ;
-(char)hasHardwareType;
@end

