/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface AWDNFCReaderSessionTagRead : PBCodable <NSCopying> {

	unsigned long long _duration;
	unsigned long long _timeDeltaFromReference;
	unsigned long long _timestamp;
	unsigned _payloadSize;
	unsigned _rawCommandCount;
	unsigned _resultCode;
	unsigned _tagType;
	unsigned _type;
	NSData* _uuidReference;
	SCD_Struct_AW6 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                           //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) char hasUuidReference; 
@property (nonatomic,retain) NSData * uuidReference;                                 //@synthesize uuidReference=_uuidReference - In the implementation block
@property (assign,nonatomic) char hasTimeDeltaFromReference; 
@property (assign,nonatomic) unsigned long long timeDeltaFromReference;              //@synthesize timeDeltaFromReference=_timeDeltaFromReference - In the implementation block
@property (assign,nonatomic) char hasType; 
@property (assign,nonatomic) unsigned type;                                          //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) char hasTagType; 
@property (assign,nonatomic) unsigned tagType;                                       //@synthesize tagType=_tagType - In the implementation block
@property (assign,nonatomic) char hasPayloadSize; 
@property (assign,nonatomic) unsigned payloadSize;                                   //@synthesize payloadSize=_payloadSize - In the implementation block
@property (assign,nonatomic) char hasDuration; 
@property (assign,nonatomic) unsigned long long duration;                            //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) char hasResultCode; 
@property (assign,nonatomic) unsigned resultCode;                                    //@synthesize resultCode=_resultCode - In the implementation block
@property (assign,nonatomic) char hasRawCommandCount; 
@property (assign,nonatomic) unsigned rawCommandCount;                               //@synthesize rawCommandCount=_rawCommandCount - In the implementation block
-(void)setUuidReference:(NSData *)arg1 ;
-(char)hasUuidReference;
-(void)setTimeDeltaFromReference:(unsigned long long)arg1 ;
-(void)setHasTimeDeltaFromReference:(char)arg1 ;
-(char)hasTimeDeltaFromReference;
-(void)setHasTagType:(char)arg1 ;
-(char)hasTagType;
-(NSData *)uuidReference;
-(unsigned long long)timeDeltaFromReference;
-(void)setRawCommandCount:(unsigned)arg1 ;
-(void)setHasRawCommandCount:(char)arg1 ;
-(char)hasRawCommandCount;
-(unsigned)rawCommandCount;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)setType:(unsigned)arg1 ;
-(unsigned)type;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(unsigned long long)duration;
-(void)setDuration:(unsigned long long)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(void)setHasType:(char)arg1 ;
-(char)hasType;
-(unsigned)resultCode;
-(unsigned)payloadSize;
-(void)setResultCode:(unsigned)arg1 ;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setHasDuration:(char)arg1 ;
-(char)hasDuration;
-(void)setPayloadSize:(unsigned)arg1 ;
-(void)setHasPayloadSize:(char)arg1 ;
-(char)hasPayloadSize;
-(void)setHasResultCode:(char)arg1 ;
-(char)hasResultCode;
-(unsigned)tagType;
-(void)setTagType:(unsigned)arg1 ;
@end

