/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:04 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData, NSString;

@interface AWDNFCSERestrictedModeEnteredEvent : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSData* _attackLog;
	unsigned _hardwareType;
	NSString* _platformIdentifier;
	NSData* _restrictedModeUUID;
	char _contactless;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) char hasContactless; 
@property (assign,nonatomic) char contactless;                           //@synthesize contactless=_contactless - In the implementation block
@property (nonatomic,readonly) char hasRestrictedModeUUID; 
@property (nonatomic,retain) NSData * restrictedModeUUID;                //@synthesize restrictedModeUUID=_restrictedModeUUID - In the implementation block
@property (nonatomic,readonly) char hasPlatformIdentifier; 
@property (nonatomic,retain) NSString * platformIdentifier;              //@synthesize platformIdentifier=_platformIdentifier - In the implementation block
@property (nonatomic,readonly) char hasAttackLog; 
@property (nonatomic,retain) NSData * attackLog;                         //@synthesize attackLog=_attackLog - In the implementation block
@property (assign,nonatomic) char hasHardwareType; 
@property (assign,nonatomic) unsigned hardwareType;                      //@synthesize hardwareType=_hardwareType - In the implementation block
-(void)setRestrictedModeUUID:(NSData *)arg1 ;
-(void)setAttackLog:(NSData *)arg1 ;
-(void)setContactless:(char)arg1 ;
-(void)setHasContactless:(char)arg1 ;
-(char)hasContactless;
-(char)hasRestrictedModeUUID;
-(char)hasPlatformIdentifier;
-(char)hasAttackLog;
-(char)contactless;
-(NSData *)restrictedModeUUID;
-(NSData *)attackLog;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(void)setHasTimestamp:(char)arg1 ;
-(NSString *)platformIdentifier;
-(void)setPlatformIdentifier:(NSString *)arg1 ;
-(unsigned)hardwareType;
-(void)setHardwareType:(unsigned)arg1 ;
-(void)setHasHardwareType:(char)arg1 ;
-(char)hasHardwareType;
@end

