/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDNFCGeneralStatistic : PBCodable <NSCopying> {

	unsigned long long _startTimestamp;
	unsigned long long _timestamp;
	unsigned _seCounterMeasureLevel;
	unsigned _totalAPNReceived;
	unsigned _totalAccessTransaction;
	unsigned _totalAuthECommerce;
	unsigned _totalBurnoutTimerCounter;
	unsigned _totalCEEnable;
	unsigned _totalCEEnabledWithMissingTransactionEndEvent;
	unsigned _totalCEEnabledWithNoFieldDetected;
	unsigned _totalCardProvisioned;
	unsigned _totalDynamicPackages;
	unsigned _totalDynamicRFParametersUpdate;
	unsigned _totalExpressFelicaTransaction;
	unsigned _totalFailureWithMissingTransactionEndEvent;
	unsigned _totalFailureWithTransactionEndEventErrors;
	unsigned _totalFelicaEMoneyTransaction;
	unsigned _totalFelicaTransitTransaction;
	unsigned _totalGenericAExpressTransaction;
	unsigned _totalLPEMCounter;
	unsigned _totalMWExceptions;
	unsigned _totalPTDatabaseCorruption;
	unsigned _totalPTKeyDeletionFailed;
	unsigned _totalPTKeys;
	unsigned _totalPeerPaymentRequest;
	unsigned _totalPeerPaymentRequestFailure;
	unsigned _totalPlasticCardModeEnable;
	unsigned _totalRestrictModeEntered;
	unsigned _totalSuccessfulCardIngestion;
	unsigned _totalSuccessfulCardIngestionWithSessionToken;
	unsigned _totalSuccessfulVAS;
	unsigned _totalTransactionEndEvent;
	unsigned _totalTransientDeactiveTimeout;
	unsigned _totalVASActivation;
	unsigned _totalVASSignup;
	unsigned _totalVASTransactionException;
	char _hasAccessExpressTransactionEnable;
	char _hasAttackLogs;
	char _hasFelicaExpressTransactionEnable;
	char _hasGenericAExpressEnable;
	SCD_Struct_AW16 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                       //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) char hasStartTimestamp; 
@property (assign,nonatomic) unsigned long long startTimestamp;                                  //@synthesize startTimestamp=_startTimestamp - In the implementation block
@property (assign,nonatomic) char hasTotalCEEnable; 
@property (assign,nonatomic) unsigned totalCEEnable;                                             //@synthesize totalCEEnable=_totalCEEnable - In the implementation block
@property (assign,nonatomic) char hasTotalCardProvisioned; 
@property (assign,nonatomic) unsigned totalCardProvisioned;                                      //@synthesize totalCardProvisioned=_totalCardProvisioned - In the implementation block
@property (assign,nonatomic) char hasTotalTransientDeactiveTimeout; 
@property (assign,nonatomic) unsigned totalTransientDeactiveTimeout;                             //@synthesize totalTransientDeactiveTimeout=_totalTransientDeactiveTimeout - In the implementation block
@property (assign,nonatomic) char hasTotalAPNReceived; 
@property (assign,nonatomic) unsigned totalAPNReceived;                                          //@synthesize totalAPNReceived=_totalAPNReceived - In the implementation block
@property (assign,nonatomic) char hasTotalRestrictModeEntered; 
@property (assign,nonatomic) unsigned totalRestrictModeEntered;                                  //@synthesize totalRestrictModeEntered=_totalRestrictModeEntered - In the implementation block
@property (assign,nonatomic) char hasTotalTransactionEndEvent; 
@property (assign,nonatomic) unsigned totalTransactionEndEvent;                                  //@synthesize totalTransactionEndEvent=_totalTransactionEndEvent - In the implementation block
@property (assign,nonatomic) char hasTotalFailureWithTransactionEndEventErrors; 
@property (assign,nonatomic) unsigned totalFailureWithTransactionEndEventErrors;                 //@synthesize totalFailureWithTransactionEndEventErrors=_totalFailureWithTransactionEndEventErrors - In the implementation block
@property (assign,nonatomic) char hasTotalFailureWithMissingTransactionEndEvent; 
@property (assign,nonatomic) unsigned totalFailureWithMissingTransactionEndEvent;                //@synthesize totalFailureWithMissingTransactionEndEvent=_totalFailureWithMissingTransactionEndEvent - In the implementation block
@property (assign,nonatomic) char hasTotalAuthECommerce; 
@property (assign,nonatomic) unsigned totalAuthECommerce;                                        //@synthesize totalAuthECommerce=_totalAuthECommerce - In the implementation block
@property (assign,nonatomic) char hasTotalVASActivation; 
@property (assign,nonatomic) unsigned totalVASActivation;                                        //@synthesize totalVASActivation=_totalVASActivation - In the implementation block
@property (assign,nonatomic) char hasTotalSuccessfulVAS; 
@property (assign,nonatomic) unsigned totalSuccessfulVAS;                                        //@synthesize totalSuccessfulVAS=_totalSuccessfulVAS - In the implementation block
@property (assign,nonatomic) char hasTotalVASSignup; 
@property (assign,nonatomic) unsigned totalVASSignup;                                            //@synthesize totalVASSignup=_totalVASSignup - In the implementation block
@property (assign,nonatomic) char hasTotalVASTransactionException; 
@property (assign,nonatomic) unsigned totalVASTransactionException;                              //@synthesize totalVASTransactionException=_totalVASTransactionException - In the implementation block
@property (assign,nonatomic) char hasTotalExpressFelicaTransaction; 
@property (assign,nonatomic) unsigned totalExpressFelicaTransaction;                             //@synthesize totalExpressFelicaTransaction=_totalExpressFelicaTransaction - In the implementation block
@property (assign,nonatomic) char hasTotalFelicaEMoneyTransaction; 
@property (assign,nonatomic) unsigned totalFelicaEMoneyTransaction;                              //@synthesize totalFelicaEMoneyTransaction=_totalFelicaEMoneyTransaction - In the implementation block
@property (assign,nonatomic) char hasTotalFelicaTransitTransaction; 
@property (assign,nonatomic) unsigned totalFelicaTransitTransaction;                             //@synthesize totalFelicaTransitTransaction=_totalFelicaTransitTransaction - In the implementation block
@property (assign,nonatomic) char hasHasFelicaExpressTransactionEnable; 
@property (assign,nonatomic) char hasFelicaExpressTransactionEnable;                             //@synthesize hasFelicaExpressTransactionEnable=_hasFelicaExpressTransactionEnable - In the implementation block
@property (assign,nonatomic) char hasTotalSuccessfulCardIngestion; 
@property (assign,nonatomic) unsigned totalSuccessfulCardIngestion;                              //@synthesize totalSuccessfulCardIngestion=_totalSuccessfulCardIngestion - In the implementation block
@property (assign,nonatomic) char hasTotalSuccessfulCardIngestionWithSessionToken; 
@property (assign,nonatomic) unsigned totalSuccessfulCardIngestionWithSessionToken;              //@synthesize totalSuccessfulCardIngestionWithSessionToken=_totalSuccessfulCardIngestionWithSessionToken - In the implementation block
@property (assign,nonatomic) char hasTotalPlasticCardModeEnable; 
@property (assign,nonatomic) unsigned totalPlasticCardModeEnable;                                //@synthesize totalPlasticCardModeEnable=_totalPlasticCardModeEnable - In the implementation block
@property (assign,nonatomic) char hasTotalAccessTransaction; 
@property (assign,nonatomic) unsigned totalAccessTransaction;                                    //@synthesize totalAccessTransaction=_totalAccessTransaction - In the implementation block
@property (assign,nonatomic) char hasHasAccessExpressTransactionEnable; 
@property (assign,nonatomic) char hasAccessExpressTransactionEnable;                             //@synthesize hasAccessExpressTransactionEnable=_hasAccessExpressTransactionEnable - In the implementation block
@property (assign,nonatomic) char hasHasAttackLogs; 
@property (assign,nonatomic) char hasAttackLogs;                                                 //@synthesize hasAttackLogs=_hasAttackLogs - In the implementation block
@property (assign,nonatomic) char hasTotalDynamicPackages; 
@property (assign,nonatomic) unsigned totalDynamicPackages;                                      //@synthesize totalDynamicPackages=_totalDynamicPackages - In the implementation block
@property (assign,nonatomic) char hasTotalPeerPaymentRequest; 
@property (assign,nonatomic) unsigned totalPeerPaymentRequest;                                   //@synthesize totalPeerPaymentRequest=_totalPeerPaymentRequest - In the implementation block
@property (assign,nonatomic) char hasTotalPeerPaymentRequestFailure; 
@property (assign,nonatomic) unsigned totalPeerPaymentRequestFailure;                            //@synthesize totalPeerPaymentRequestFailure=_totalPeerPaymentRequestFailure - In the implementation block
@property (assign,nonatomic) char hasHasGenericAExpressEnable; 
@property (assign,nonatomic) char hasGenericAExpressEnable;                                      //@synthesize hasGenericAExpressEnable=_hasGenericAExpressEnable - In the implementation block
@property (assign,nonatomic) char hasTotalGenericAExpressTransaction; 
@property (assign,nonatomic) unsigned totalGenericAExpressTransaction;                           //@synthesize totalGenericAExpressTransaction=_totalGenericAExpressTransaction - In the implementation block
@property (assign,nonatomic) char hasTotalDynamicRFParametersUpdate; 
@property (assign,nonatomic) unsigned totalDynamicRFParametersUpdate;                            //@synthesize totalDynamicRFParametersUpdate=_totalDynamicRFParametersUpdate - In the implementation block
@property (assign,nonatomic) char hasTotalCEEnabledWithNoFieldDetected; 
@property (assign,nonatomic) unsigned totalCEEnabledWithNoFieldDetected;                         //@synthesize totalCEEnabledWithNoFieldDetected=_totalCEEnabledWithNoFieldDetected - In the implementation block
@property (assign,nonatomic) char hasTotalCEEnabledWithMissingTransactionEndEvent; 
@property (assign,nonatomic) unsigned totalCEEnabledWithMissingTransactionEndEvent;              //@synthesize totalCEEnabledWithMissingTransactionEndEvent=_totalCEEnabledWithMissingTransactionEndEvent - In the implementation block
@property (assign,nonatomic) char hasTotalPTKeys; 
@property (assign,nonatomic) unsigned totalPTKeys;                                               //@synthesize totalPTKeys=_totalPTKeys - In the implementation block
@property (assign,nonatomic) char hasTotalPTDatabaseCorruption; 
@property (assign,nonatomic) unsigned totalPTDatabaseCorruption;                                 //@synthesize totalPTDatabaseCorruption=_totalPTDatabaseCorruption - In the implementation block
@property (assign,nonatomic) char hasTotalPTKeyDeletionFailed; 
@property (assign,nonatomic) unsigned totalPTKeyDeletionFailed;                                  //@synthesize totalPTKeyDeletionFailed=_totalPTKeyDeletionFailed - In the implementation block
@property (assign,nonatomic) char hasTotalLPEMCounter; 
@property (assign,nonatomic) unsigned totalLPEMCounter;                                          //@synthesize totalLPEMCounter=_totalLPEMCounter - In the implementation block
@property (assign,nonatomic) char hasSeCounterMeasureLevel; 
@property (assign,nonatomic) unsigned seCounterMeasureLevel;                                     //@synthesize seCounterMeasureLevel=_seCounterMeasureLevel - In the implementation block
@property (assign,nonatomic) char hasTotalBurnoutTimerCounter; 
@property (assign,nonatomic) unsigned totalBurnoutTimerCounter;                                  //@synthesize totalBurnoutTimerCounter=_totalBurnoutTimerCounter - In the implementation block
@property (assign,nonatomic) char hasTotalMWExceptions; 
@property (assign,nonatomic) unsigned totalMWExceptions;                                         //@synthesize totalMWExceptions=_totalMWExceptions - In the implementation block
-(void)setTotalCEEnable:(unsigned)arg1 ;
-(void)setTotalCardProvisioned:(unsigned)arg1 ;
-(void)setTotalTransientDeactiveTimeout:(unsigned)arg1 ;
-(void)setTotalAPNReceived:(unsigned)arg1 ;
-(void)setTotalRestrictModeEntered:(unsigned)arg1 ;
-(void)setTotalTransactionEndEvent:(unsigned)arg1 ;
-(void)setTotalFailureWithTransactionEndEventErrors:(unsigned)arg1 ;
-(void)setTotalAuthECommerce:(unsigned)arg1 ;
-(void)setTotalVASActivation:(unsigned)arg1 ;
-(void)setTotalSuccessfulVAS:(unsigned)arg1 ;
-(void)setTotalVASSignup:(unsigned)arg1 ;
-(void)setTotalVASTransactionException:(unsigned)arg1 ;
-(void)setTotalExpressFelicaTransaction:(unsigned)arg1 ;
-(void)setTotalFelicaEMoneyTransaction:(unsigned)arg1 ;
-(void)setTotalFelicaTransitTransaction:(unsigned)arg1 ;
-(void)setTotalSuccessfulCardIngestion:(unsigned)arg1 ;
-(void)setTotalSuccessfulCardIngestionWithSessionToken:(unsigned)arg1 ;
-(void)setTotalPlasticCardModeEnable:(unsigned)arg1 ;
-(void)setTotalAccessTransaction:(unsigned)arg1 ;
-(void)setHasAttackLogs:(char)arg1 ;
-(void)setTotalPeerPaymentRequest:(unsigned)arg1 ;
-(void)setTotalPeerPaymentRequestFailure:(unsigned)arg1 ;
-(void)setTotalGenericAExpressTransaction:(unsigned)arg1 ;
-(void)setTotalDynamicRFParametersUpdate:(unsigned)arg1 ;
-(void)setTotalPTKeys:(unsigned)arg1 ;
-(void)setTotalPTDatabaseCorruption:(unsigned)arg1 ;
-(void)setTotalPTKeyDeletionFailed:(unsigned)arg1 ;
-(void)setTotalBurnoutTimerCounter:(unsigned)arg1 ;
-(void)setTotalMWExceptions:(unsigned)arg1 ;
-(void)setHasTotalCEEnable:(char)arg1 ;
-(char)hasTotalCEEnable;
-(void)setHasTotalCardProvisioned:(char)arg1 ;
-(char)hasTotalCardProvisioned;
-(void)setHasTotalTransientDeactiveTimeout:(char)arg1 ;
-(char)hasTotalTransientDeactiveTimeout;
-(void)setHasTotalAPNReceived:(char)arg1 ;
-(char)hasTotalAPNReceived;
-(void)setHasTotalRestrictModeEntered:(char)arg1 ;
-(char)hasTotalRestrictModeEntered;
-(void)setHasTotalTransactionEndEvent:(char)arg1 ;
-(char)hasTotalTransactionEndEvent;
-(void)setHasTotalFailureWithTransactionEndEventErrors:(char)arg1 ;
-(char)hasTotalFailureWithTransactionEndEventErrors;
-(void)setTotalFailureWithMissingTransactionEndEvent:(unsigned)arg1 ;
-(void)setHasTotalFailureWithMissingTransactionEndEvent:(char)arg1 ;
-(char)hasTotalFailureWithMissingTransactionEndEvent;
-(void)setHasTotalAuthECommerce:(char)arg1 ;
-(char)hasTotalAuthECommerce;
-(void)setHasTotalVASActivation:(char)arg1 ;
-(char)hasTotalVASActivation;
-(void)setHasTotalSuccessfulVAS:(char)arg1 ;
-(char)hasTotalSuccessfulVAS;
-(void)setHasTotalVASSignup:(char)arg1 ;
-(char)hasTotalVASSignup;
-(void)setHasTotalVASTransactionException:(char)arg1 ;
-(char)hasTotalVASTransactionException;
-(void)setHasTotalExpressFelicaTransaction:(char)arg1 ;
-(char)hasTotalExpressFelicaTransaction;
-(void)setHasTotalFelicaEMoneyTransaction:(char)arg1 ;
-(char)hasTotalFelicaEMoneyTransaction;
-(void)setHasTotalFelicaTransitTransaction:(char)arg1 ;
-(char)hasTotalFelicaTransitTransaction;
-(void)setHasFelicaExpressTransactionEnable:(char)arg1 ;
-(void)setHasHasFelicaExpressTransactionEnable:(char)arg1 ;
-(char)hasHasFelicaExpressTransactionEnable;
-(void)setHasTotalSuccessfulCardIngestion:(char)arg1 ;
-(char)hasTotalSuccessfulCardIngestion;
-(void)setHasTotalSuccessfulCardIngestionWithSessionToken:(char)arg1 ;
-(char)hasTotalSuccessfulCardIngestionWithSessionToken;
-(void)setHasTotalPlasticCardModeEnable:(char)arg1 ;
-(char)hasTotalPlasticCardModeEnable;
-(void)setHasTotalAccessTransaction:(char)arg1 ;
-(char)hasTotalAccessTransaction;
-(void)setHasAccessExpressTransactionEnable:(char)arg1 ;
-(void)setHasHasAccessExpressTransactionEnable:(char)arg1 ;
-(char)hasHasAccessExpressTransactionEnable;
-(void)setHasHasAttackLogs:(char)arg1 ;
-(char)hasHasAttackLogs;
-(void)setTotalDynamicPackages:(unsigned)arg1 ;
-(void)setHasTotalDynamicPackages:(char)arg1 ;
-(char)hasTotalDynamicPackages;
-(void)setHasTotalPeerPaymentRequest:(char)arg1 ;
-(char)hasTotalPeerPaymentRequest;
-(void)setHasTotalPeerPaymentRequestFailure:(char)arg1 ;
-(char)hasTotalPeerPaymentRequestFailure;
-(void)setHasGenericAExpressEnable:(char)arg1 ;
-(void)setHasHasGenericAExpressEnable:(char)arg1 ;
-(char)hasHasGenericAExpressEnable;
-(void)setHasTotalGenericAExpressTransaction:(char)arg1 ;
-(char)hasTotalGenericAExpressTransaction;
-(void)setHasTotalDynamicRFParametersUpdate:(char)arg1 ;
-(char)hasTotalDynamicRFParametersUpdate;
-(void)setTotalCEEnabledWithNoFieldDetected:(unsigned)arg1 ;
-(void)setHasTotalCEEnabledWithNoFieldDetected:(char)arg1 ;
-(char)hasTotalCEEnabledWithNoFieldDetected;
-(void)setTotalCEEnabledWithMissingTransactionEndEvent:(unsigned)arg1 ;
-(void)setHasTotalCEEnabledWithMissingTransactionEndEvent:(char)arg1 ;
-(char)hasTotalCEEnabledWithMissingTransactionEndEvent;
-(void)setHasTotalPTKeys:(char)arg1 ;
-(char)hasTotalPTKeys;
-(void)setHasTotalPTDatabaseCorruption:(char)arg1 ;
-(char)hasTotalPTDatabaseCorruption;
-(void)setHasTotalPTKeyDeletionFailed:(char)arg1 ;
-(char)hasTotalPTKeyDeletionFailed;
-(void)setTotalLPEMCounter:(unsigned)arg1 ;
-(void)setHasTotalLPEMCounter:(char)arg1 ;
-(char)hasTotalLPEMCounter;
-(void)setSeCounterMeasureLevel:(unsigned)arg1 ;
-(void)setHasSeCounterMeasureLevel:(char)arg1 ;
-(char)hasSeCounterMeasureLevel;
-(void)setHasTotalBurnoutTimerCounter:(char)arg1 ;
-(char)hasTotalBurnoutTimerCounter;
-(void)setHasTotalMWExceptions:(char)arg1 ;
-(char)hasTotalMWExceptions;
-(unsigned)totalCEEnable;
-(unsigned)totalCardProvisioned;
-(unsigned)totalTransientDeactiveTimeout;
-(unsigned)totalAPNReceived;
-(unsigned)totalRestrictModeEntered;
-(unsigned)totalTransactionEndEvent;
-(unsigned)totalFailureWithTransactionEndEventErrors;
-(unsigned)totalFailureWithMissingTransactionEndEvent;
-(unsigned)totalAuthECommerce;
-(unsigned)totalVASActivation;
-(unsigned)totalSuccessfulVAS;
-(unsigned)totalVASSignup;
-(unsigned)totalVASTransactionException;
-(unsigned)totalExpressFelicaTransaction;
-(unsigned)totalFelicaEMoneyTransaction;
-(unsigned)totalFelicaTransitTransaction;
-(char)hasFelicaExpressTransactionEnable;
-(unsigned)totalSuccessfulCardIngestion;
-(unsigned)totalSuccessfulCardIngestionWithSessionToken;
-(unsigned)totalPlasticCardModeEnable;
-(unsigned)totalAccessTransaction;
-(char)hasAccessExpressTransactionEnable;
-(char)hasAttackLogs;
-(unsigned)totalDynamicPackages;
-(unsigned)totalPeerPaymentRequest;
-(unsigned)totalPeerPaymentRequestFailure;
-(char)hasGenericAExpressEnable;
-(unsigned)totalGenericAExpressTransaction;
-(unsigned)totalDynamicRFParametersUpdate;
-(unsigned)totalCEEnabledWithNoFieldDetected;
-(unsigned)totalCEEnabledWithMissingTransactionEndEvent;
-(unsigned)totalPTKeys;
-(unsigned)totalPTDatabaseCorruption;
-(unsigned)totalPTKeyDeletionFailed;
-(unsigned)totalLPEMCounter;
-(unsigned)seCounterMeasureLevel;
-(unsigned)totalBurnoutTimerCounter;
-(unsigned)totalMWExceptions;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(unsigned long long)startTimestamp;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setStartTimestamp:(unsigned long long)arg1 ;
-(void)setHasStartTimestamp:(char)arg1 ;
-(char)hasStartTimestamp;
@end

