/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray;

@interface AWDNFCExpressTransactionStatistic : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _expressModeConfiguration;
	NSMutableArray* _transactionLists;
	SCD_Struct_AW5 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                   //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,retain) NSMutableArray * transactionLists;              //@synthesize transactionLists=_transactionLists - In the implementation block
@property (assign,nonatomic) char hasExpressModeConfiguration; 
@property (assign,nonatomic) unsigned expressModeConfiguration;              //@synthesize expressModeConfiguration=_expressModeConfiguration - In the implementation block
+(Class)transactionListType;
-(void)addTransactionList:(id)arg1 ;
-(unsigned long long)transactionListsCount;
-(void)clearTransactionLists;
-(id)transactionListAtIndex:(unsigned long long)arg1 ;
-(void)setExpressModeConfiguration:(unsigned)arg1 ;
-(void)setHasExpressModeConfiguration:(char)arg1 ;
-(char)hasExpressModeConfiguration;
-(NSMutableArray *)transactionLists;
-(void)setTransactionLists:(NSMutableArray *)arg1 ;
-(unsigned)expressModeConfiguration;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(void)setHasTimestamp:(char)arg1 ;
@end

