/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:04 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface AWDNFCCardIngestionSessionStateChangeEvent : PBCodable <NSCopying> {

	unsigned long long _timeDeltaFromReference;
	unsigned long long _timestamp;
	unsigned _cardValidationStatus;
	unsigned _currentBatteryLevel;
	unsigned _sPID;
	unsigned _sessionStatus;
	unsigned _spStatusCode;
	unsigned _state;
	unsigned _technology;
	NSData* _uuidReference;
	SCD_Struct_AW7 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                           //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) char hasUuidReference; 
@property (nonatomic,retain) NSData * uuidReference;                                 //@synthesize uuidReference=_uuidReference - In the implementation block
@property (assign,nonatomic) char hasTimeDeltaFromReference; 
@property (assign,nonatomic) unsigned long long timeDeltaFromReference;              //@synthesize timeDeltaFromReference=_timeDeltaFromReference - In the implementation block
@property (assign,nonatomic) char hasState; 
@property (assign,nonatomic) unsigned state;                                         //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) char hasTechnology; 
@property (assign,nonatomic) unsigned technology;                                    //@synthesize technology=_technology - In the implementation block
@property (assign,nonatomic) char hasSpStatusCode; 
@property (assign,nonatomic) unsigned spStatusCode;                                  //@synthesize spStatusCode=_spStatusCode - In the implementation block
@property (assign,nonatomic) char hasCardValidationStatus; 
@property (assign,nonatomic) unsigned cardValidationStatus;                          //@synthesize cardValidationStatus=_cardValidationStatus - In the implementation block
@property (assign,nonatomic) char hasSessionStatus; 
@property (assign,nonatomic) unsigned sessionStatus;                                 //@synthesize sessionStatus=_sessionStatus - In the implementation block
@property (assign,nonatomic) char hasSPID; 
@property (assign,nonatomic) unsigned sPID;                                          //@synthesize sPID=_sPID - In the implementation block
@property (assign,nonatomic) char hasCurrentBatteryLevel; 
@property (assign,nonatomic) unsigned currentBatteryLevel;                           //@synthesize currentBatteryLevel=_currentBatteryLevel - In the implementation block
-(void)setUuidReference:(NSData *)arg1 ;
-(char)hasUuidReference;
-(void)setTimeDeltaFromReference:(unsigned long long)arg1 ;
-(void)setHasTimeDeltaFromReference:(char)arg1 ;
-(char)hasTimeDeltaFromReference;
-(void)setCurrentBatteryLevel:(unsigned)arg1 ;
-(void)setHasCurrentBatteryLevel:(char)arg1 ;
-(char)hasCurrentBatteryLevel;
-(NSData *)uuidReference;
-(unsigned long long)timeDeltaFromReference;
-(void)setHasSpStatusCode:(char)arg1 ;
-(char)hasSpStatusCode;
-(void)setCardValidationStatus:(unsigned)arg1 ;
-(void)setHasCardValidationStatus:(char)arg1 ;
-(char)hasCardValidationStatus;
-(void)setHasSessionStatus:(char)arg1 ;
-(char)hasSessionStatus;
-(void)setSPID:(unsigned)arg1 ;
-(void)setHasSPID:(char)arg1 ;
-(char)hasSPID;
-(unsigned)cardValidationStatus;
-(unsigned)sPID;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned)state;
-(void)setState:(unsigned)arg1 ;
-(unsigned)sessionStatus;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(void)setHasTimestamp:(char)arg1 ;
-(char)hasState;
-(void)setHasState:(char)arg1 ;
-(unsigned)technology;
-(void)setTechnology:(unsigned)arg1 ;
-(void)setSessionStatus:(unsigned)arg1 ;
-(unsigned)currentBatteryLevel;
-(unsigned)spStatusCode;
-(void)setSpStatusCode:(unsigned)arg1 ;
-(void)setHasTechnology:(char)arg1 ;
-(char)hasTechnology;
@end

