/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NFAWDEventProtocol.h>

@class AWDNFCHCIEndOfTransactionV2Event, NSData, NSString;

@interface NFAWDEndOfTransactionV2 : NSObject <NFAWDEventProtocol> {

	char _isBlacklisted;
	char _hasExpiryDate;
	unsigned _version;
	unsigned _command;
	unsigned _commandParam1;
	unsigned _commandResult;
	unsigned _transactionStatus;
	unsigned _transactionType;
	unsigned _informative;
	unsigned _spid;
	unsigned _transactionCategory;
	unsigned _transactionExtension;
	unsigned _transactionInProgress;
	unsigned _currencyCode;
	unsigned _expressType;
	unsigned _totalRSSISamples;
	unsigned _avgRSSIValue;
	unsigned _maxRSSIValue;
	unsigned _minRSSIValue;
	unsigned _accessUniversityCode;
	unsigned _issuerCityCode;
	unsigned _endEventInterface;
	unsigned _sfiRead;
	unsigned _sfiUpdated;
	unsigned _multiTagState;
	AWDNFCHCIEndOfTransactionV2Event* _metric;

}

@property (assign,nonatomic) unsigned version;                                       //@synthesize version=_version - In the implementation block
@property (nonatomic,retain) NSData * aid; 
@property (assign,nonatomic) unsigned command;                                       //@synthesize command=_command - In the implementation block
@property (assign,nonatomic) unsigned commandParam1;                                 //@synthesize commandParam1=_commandParam1 - In the implementation block
@property (assign,nonatomic) unsigned commandResult;                                 //@synthesize commandResult=_commandResult - In the implementation block
@property (nonatomic,retain) NSData * transactionId; 
@property (assign,nonatomic) unsigned transactionStatus;                             //@synthesize transactionStatus=_transactionStatus - In the implementation block
@property (assign,nonatomic) unsigned transactionType;                               //@synthesize transactionType=_transactionType - In the implementation block
@property (assign,nonatomic) unsigned informative;                                   //@synthesize informative=_informative - In the implementation block
@property (assign,nonatomic) unsigned spid;                                          //@synthesize spid=_spid - In the implementation block
@property (nonatomic,retain) NSData * stationId; 
@property (assign,nonatomic) unsigned transactionCategory;                           //@synthesize transactionCategory=_transactionCategory - In the implementation block
@property (assign,nonatomic) unsigned transactionExtension;                          //@synthesize transactionExtension=_transactionExtension - In the implementation block
@property (assign,nonatomic) unsigned transactionInProgress;                         //@synthesize transactionInProgress=_transactionInProgress - In the implementation block
@property (assign,nonatomic) unsigned currencyCode;                                  //@synthesize currencyCode=_currencyCode - In the implementation block
@property (assign,nonatomic) unsigned expressType;                                   //@synthesize expressType=_expressType - In the implementation block
@property (assign,nonatomic) char isBlacklisted;                                     //@synthesize isBlacklisted=_isBlacklisted - In the implementation block
@property (assign,nonatomic) char hasExpiryDate;                                     //@synthesize hasExpiryDate=_hasExpiryDate - In the implementation block
@property (nonatomic,retain) NSData * terminalIdentifier; 
@property (assign,nonatomic) unsigned totalRSSISamples;                              //@synthesize totalRSSISamples=_totalRSSISamples - In the implementation block
@property (assign,nonatomic) unsigned avgRSSIValue;                                  //@synthesize avgRSSIValue=_avgRSSIValue - In the implementation block
@property (assign,nonatomic) unsigned maxRSSIValue;                                  //@synthesize maxRSSIValue=_maxRSSIValue - In the implementation block
@property (assign,nonatomic) unsigned minRSSIValue;                                  //@synthesize minRSSIValue=_minRSSIValue - In the implementation block
@property (assign,nonatomic) unsigned accessUniversityCode;                          //@synthesize accessUniversityCode=_accessUniversityCode - In the implementation block
@property (assign,nonatomic) unsigned issuerCityCode;                                //@synthesize issuerCityCode=_issuerCityCode - In the implementation block
@property (assign,nonatomic) unsigned endEventInterface;                             //@synthesize endEventInterface=_endEventInterface - In the implementation block
@property (assign,nonatomic) unsigned sfiRead;                                       //@synthesize sfiRead=_sfiRead - In the implementation block
@property (assign,nonatomic) unsigned sfiUpdated;                                    //@synthesize sfiUpdated=_sfiUpdated - In the implementation block
@property (assign,nonatomic) unsigned multiTagState;                                 //@synthesize multiTagState=_multiTagState - In the implementation block
@property (nonatomic,retain) AWDNFCHCIEndOfTransactionV2Event * metric;              //@synthesize metric=_metric - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setTerminalIdentifier:(NSData *)arg1 ;
-(void)setCommandParam1:(unsigned)arg1 ;
-(void)setCommandResult:(unsigned)arg1 ;
-(void)setExpressType:(unsigned)arg1 ;
-(void)setHasExpiryDate:(char)arg1 ;
-(void)setInformative:(unsigned)arg1 ;
-(void)setTransactionCategory:(unsigned)arg1 ;
-(void)setTransactionExtension:(unsigned)arg1 ;
-(void)setTotalRSSISamples:(unsigned)arg1 ;
-(void)setAvgRSSIValue:(unsigned)arg1 ;
-(void)setMaxRSSIValue:(unsigned)arg1 ;
-(void)setMinRSSIValue:(unsigned)arg1 ;
-(void)setAccessUniversityCode:(unsigned)arg1 ;
-(void)setIssuerCityCode:(unsigned)arg1 ;
-(void)setEndEventInterface:(unsigned)arg1 ;
-(void)setSfiRead:(unsigned)arg1 ;
-(void)setSfiUpdated:(unsigned)arg1 ;
-(void)setMultiTagState:(unsigned)arg1 ;
-(unsigned)commandParam1;
-(unsigned)commandResult;
-(unsigned)expressType;
-(char)hasExpiryDate;
-(unsigned)transactionCategory;
-(unsigned)transactionExtension;
-(NSData *)terminalIdentifier;
-(unsigned)totalRSSISamples;
-(unsigned)avgRSSIValue;
-(unsigned)maxRSSIValue;
-(unsigned)minRSSIValue;
-(unsigned)accessUniversityCode;
-(unsigned)issuerCityCode;
-(unsigned)endEventInterface;
-(unsigned)sfiRead;
-(unsigned)sfiUpdated;
-(unsigned)multiTagState;
-(unsigned)getMetricId;
-(id)getMetric;
-(void)updateUUID:(id)arg1 withUUIDRefTimestamp:(unsigned long long)arg2 ;
-(unsigned long long)updateTransactionStateInfoWithPreviousState:(unsigned long long)arg1 ;
-(void)setStationId:(NSData *)arg1 ;
-(NSData *)stationId;
-(id)init;
-(unsigned)currencyCode;
-(unsigned)version;
-(void)setCurrencyCode:(unsigned)arg1 ;
-(void)setVersion:(unsigned)arg1 ;
-(unsigned)command;
-(AWDNFCHCIEndOfTransactionV2Event *)metric;
-(void)setMetric:(AWDNFCHCIEndOfTransactionV2Event *)arg1 ;
-(void)setCommand:(unsigned)arg1 ;
-(NSData *)transactionId;
-(void)setTransactionType:(unsigned)arg1 ;
-(void)setTransactionStatus:(unsigned)arg1 ;
-(void)setTransactionId:(NSData *)arg1 ;
-(unsigned)transactionType;
-(unsigned)transactionStatus;
-(unsigned)informative;
-(char)isBlacklisted;
-(unsigned)transactionInProgress;
-(void)setTransactionInProgress:(unsigned)arg1 ;
-(void)setIsBlacklisted:(char)arg1 ;
-(NSData *)aid;
-(void)setAid:(NSData *)arg1 ;
-(unsigned)spid;
-(void)setSpid:(unsigned)arg1 ;
@end

