/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:04 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFJSONEncoder : NSObject
+(id)encoder;
-(id)_JSONCompatibleArray:(id)arg1 ;
-(id)_JSONCompatibleDictionary:(id)arg1 ;
-(id)stringFromDictionary:(id)arg1 ;
-(id)stringFromArray:(id)arg1 ;
@end

