/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSData, NSArray;


@protocol NFTagF
@property (nonatomic,copy,readonly) NSData * IDm; 
@property (nonatomic,copy,readonly) NSData * PMm; 
@property (nonatomic,copy,readonly) NSData * SystemCode; 
@property (nonatomic,copy,readonly) NSArray * allSystemCodes; 
@required
-(NSData *)IDm;
-(NSData *)PMm;
-(NSData *)SystemCode;
-(NSArray *)allSystemCodes;

@end

