/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSData;


@protocol NFTagA
@property (nonatomic,copy,readonly) NSData * atqa; 
@property (nonatomic,copy,readonly) NSData * sak; 
@property (nonatomic,copy,readonly) NSData * historicalBytes; 
@property (nonatomic,copy,readonly) NSData * selectedAID; 
@required
-(NSData *)selectedAID;
-(NSData *)atqa;
-(NSData *)sak;
-(NSData *)historicalBytes;

@end

