/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source;
@class NSObject;

@interface NFTimer : NSObject {

	NSObject*<OS_dispatch_source> _src;
	unsigned long long _popTimeInSeconds;
	BOOL _monotonic;

}
-(void)dealloc;
-(id)description;
-(void)stopTimer;
-(void)startTimer:(double)arg1 ;
-(id)initWithCallback:(/*^block*/id)arg1 queue:(id)arg2 ;
-(void)startTimer:(double)arg1 leeway:(double)arg2 ;
-(id)initSleepTimerWithCallback:(/*^block*/id)arg1 queue:(id)arg2 ;
@end

