/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:53 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/swift/libswiftCoreAudio.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtCV9CoreAudio25ManagedAudioChannelLayoutP33_429D68E17F2C221C283DB52CAE70232C7Storage : _UKNOWN_SUPERCLASS_ {

	 audioChannelLayoutPointer;
	 deallocator;

}
@end

