/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:53:01 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/log/liblog_AppStoreDaemon.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <liblog_AppStoreDaemon.dylib/liblog_AppStoreDaemon.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray;

@interface LogTransactions : PBCodable <NSCopying> {

	NSMutableArray* _transactionIDs;

}

@property (nonatomic,retain) NSMutableArray * transactionIDs;              //@synthesize transactionIDs=_transactionIDs - In the implementation block
+(Class)transactionIDType;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(id)formattedText;
-(unsigned long long)transactionIDsCount;
-(NSMutableArray *)transactionIDs;
-(void)addTransactionID:(id)arg1 ;
-(void)clearTransactionIDs;
-(id)transactionIDAtIndex:(unsigned long long)arg1 ;
-(void)setTransactionIDs:(NSMutableArray *)arg1 ;
@end

