/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:50:54 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/system/libsystem_blocks.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreFoundation/NSBlock.h>

@interface __NSStackBlock__ : NSBlock
-(id)retain;
-(oneway void)release;
-(unsigned long long)retainCount;
-(id)autorelease;
@end

