/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:53:01 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libSLAMDynamic.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SLAMObjC : NSObject
+(id)PerformScript:(unsigned long long)arg1 seHandle:(id)arg2 logSink:(id)arg3 ;
+(id)PerformRecovery:(id)arg1 logSink:(id)arg2 ;
+(id)PerformScript:(unsigned long long)arg1 sefwPath:(id)arg2 seHandle:(id)arg3 logSink:(id)arg4 ;
@end

