/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:21 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface HerculesVCReader : NSObject
+(id)getCurrentTransitSummary:(id)arg1 withError:(id*)arg2 ;
+(id)getBalanceForPass:(unsigned long long)arg1 withRiderClass:(unsigned char)arg2 withTransitSummary:(id)arg3 withRTAData:(id)arg4 forCity:(id)arg5 withError:(id*)arg6 ;
+(id)readBalancesFromVC:(id)arg1 forCity:(id)arg2 withError:(id*)arg3 ;
@end

