/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:08 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
@interface __SwiftNativeNSMutableArrayBase : NSObject {

	RefCounts<swift::RefCountBitsT<swift::RefCountIsInline>> refCounts;

}
+(char)automaticallyNotifiesObserversForKey:(id)arg1 ;
-(id)retain;
-(oneway void)release;
-(unsigned long long)retainCount;
-(id)autorelease;
-(char)_tryRetain;
-(char)_isDeallocating;
-(void)dealloc;
-(char)retainWeakReference;
-(char)allowsWeakReference;
-(void)_noteAssociatedObjects;
-(void)_setWeaklyReferenced;
-(id)initWithCoder:(id)arg1 ;
@end

