/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:08 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct {
	unsigned long long field1;
	id field2;
	unsigned long long field3;
	unsigned long long field4[5];
} SCD_Struct_Sw0;

typedef struct {
	long long field1;
	long long field2;
} SCD_Struct_Sw1;

typedef struct _NSZone* NSZoneRef;

typedef struct _cxx_atomic_impl<swift::RefCountBitsT<swift::RefCountIsInline>, std::__1::__cxx_atomic_base_impl<swift::RefCountBitsT<swift::RefCountIsInline>>> {
	ARefCountBitsT<swift::RefCountIsInline> __a_value;
} cxx_atomic_impl<swift::RefCountBitsT<swift::RefCountIsInline>, std::__1::__cxx_atomic_base_impl<swift::RefCountBitsT<swift::RefCountIsInline>>>;

typedef struct atomic<swift::RefCountBitsT<swift::RefCountIsInline>> {
	cxx_atomic_impl<swift::RefCountBitsT<swift::RefCountIsInline>, std::__1::__cxx_atomic_base_impl<swift::RefCountBitsT<swift::RefCountIsInline>>> __a_;
} atomic<swift::RefCountBitsT<swift::RefCountIsInline>>;

typedef struct RefCounts<swift::RefCountBitsT<swift::RefCountIsInline>> {
	atomic<swift::RefCountBitsT<swift::RefCountIsInline>> refCounts;
} RefCounts<swift::RefCountBitsT<swift::RefCountIsInline>>;

typedef const struct OpaqueValue* OpaqueValueRef;

