/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:08 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libswiftCore.dylib/Swift.__SwiftNativeNSEnumerator.h>
#import <libobjc.A.dylib/Swift._NSEnumerator.h>

@interface Swift.__SwiftEmptyNSEnumerator : Swift.__SwiftNativeNSEnumerator <Swift._NSEnumerator>
-(id)init;
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3 ;
-(id)nextObject;
-(id)initWithCoder:(id)arg1 ;
@end

