/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:08 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/Swift.__SwiftNativeNSArrayWithContiguousStorage.h>

@interface Swift.__SwiftDeferredNSArray : Swift.__SwiftNativeNSArrayWithContiguousStorage {

	 _heapBufferBridged_DoNotUse;
	 _nativeStorage;

}

@property (readonly,nonatomic) long long count; 
-(long long)count;
@end

