/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:14 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libMemoryResourceException.dylib/libMemoryResourceException.dylib-Structs.h>
@class NSMutableArray, NSString, NSArray, NSDictionary;

@interface FPProcess : NSObject {

	int _pid;
	char _is64bit;
	char _isTranslated;
	int _idleExitStatus;
	NSMutableArray* _errors;
	NSMutableArray* _warnings;
	NSMutableArray* _globalErrors;
	char _hiddenFromDisplay;
	NSString* _name;
	NSArray* _memoryRegions;
	NSString* _displayString;
	unsigned long long _pageSize;

}

@property (assign,nonatomic) char is64bit;                               //@synthesize is64bit=_is64bit - In the implementation block
@property (assign,nonatomic) char isTranslated;                          //@synthesize isTranslated=_isTranslated - In the implementation block
@property (nonatomic,retain) NSString * displayString;                   //@synthesize displayString=_displayString - In the implementation block
@property (assign,nonatomic) unsigned long long pageSize;                //@synthesize pageSize=_pageSize - In the implementation block
@property (nonatomic,retain) NSArray * memoryRegions;                    //@synthesize memoryRegions=_memoryRegions - In the implementation block
@property (assign,nonatomic) int pid;                                    //@synthesize pid=_pid - In the implementation block
@property (nonatomic,copy) NSString * name;                              //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) int idleExitStatus;                       //@synthesize idleExitStatus=_idleExitStatus - In the implementation block
@property (assign,nonatomic) char hiddenFromDisplay;                     //@synthesize hiddenFromDisplay=_hiddenFromDisplay - In the implementation block
@property (nonatomic,readonly) NSDictionary * auxData; 
@property (nonatomic,readonly) char breakDownPhysFootprint; 
+(id)_nameForBsdInfo:(proc_bsdinfo*)arg1 ;
+(id)processWithBsdInfo:(proc_bsdinfo*)arg1 ;
+(id)_nameForBsdInfoCommName:(proc_bsdinfo*)arg1 ;
+(id)processWithPid:(int)arg1 ;
+(id)allProcessesExcludingPids:(id)arg1 ;
+(id)pidsForStringDescriptions:(id)arg1 errors:(id*)arg2 ;
+(id)childPidsForPids:(id)arg1 ;
+(id)removeIdleExitCleanProcessesFrom:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)init;
-(NSString *)name;
-(void)setName:(NSString *)arg1 ;
-(int)pid;
-(void)setDisplayString:(NSString *)arg1 ;
-(char)isTranslated;
-(id)warnings;
-(NSString *)displayString;
-(id)errors;
-(void)setPid:(int)arg1 ;
-(void)setPageSize:(unsigned long long)arg1 ;
-(unsigned long long)pageSize;
-(void)gatherData;
-(id)initWithBsdInfo:(proc_bsdinfo*)arg1 ;
-(char)_populateTask;
-(char)_isAlive;
-(void)setMemoryRegions:(NSArray *)arg1 ;
-(unsigned long long)_gatherPageSize;
-(NSDictionary *)auxData;
-(int)idleExitStatus;
-(char)breakDownPhysFootprint;
-(void)_addGlobalError:(id)arg1 ;
-(id)globalErrors;
-(id)asNumber;
-(char)is64bit;
-(void)setIs64bit:(char)arg1 ;
-(void)setIsTranslated:(char)arg1 ;
-(NSArray *)memoryRegions;
-(char)hiddenFromDisplay;
-(void)setHiddenFromDisplay:(char)arg1 ;
@end

