/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:14 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libMemoryResourceException.dylib/libMemoryResourceException.dylib-Structs.h>
#import <libobjc.A.dylib/FPOutputFormatter.h>

@class NSMutableDictionary, NSMutableArray, NSMutableSet, NSString;

@interface MREOutputFormatterInMemory : NSObject <FPOutputFormatter> {

	char _isPageSizeSet;
	char _verbose;
	NSMutableDictionary* _data;
	NSMutableArray* _processes;
	NSMutableSet* _addedProcessGroups;

}

@property (nonatomic,retain) NSMutableDictionary * data;                     //@synthesize data=_data - In the implementation block
@property (nonatomic,retain) NSMutableArray * processes;                     //@synthesize processes=_processes - In the implementation block
@property (nonatomic,retain) NSMutableSet * addedProcessGroups;              //@synthesize addedProcessGroups=_addedProcessGroups - In the implementation block
@property (assign,nonatomic) char isPageSizeSet;                             //@synthesize isPageSizeSet=_isPageSizeSet - In the implementation block
@property (assign,nonatomic) char verbose;                                   //@synthesize verbose=_verbose - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(NSMutableDictionary *)data;
-(void)setData:(NSMutableDictionary *)arg1 ;
-(NSMutableArray *)processes;
-(char)verbose;
-(void)setVerbose:(char)arg1 ;
-(void)printSummaryCategories:(id)arg1 total:(SCD_Struct_FP0*)arg2 hadErrors:(char)arg3 ;
-(id)dataForCategories:(id)arg1 ;
-(void)printProcessHeader:(id)arg1 ;
-(void)endProcessHeader:(id)arg1 ;
-(void)printProcessTotal:(id)arg1 forProcess:(id)arg2 ;
-(void)printProcessCategories:(id)arg1 total:(SCD_Struct_FP0*)arg2 ;
-(void)printSharedCategories:(id)arg1 sharedWith:(id)arg2 forProcess:(id)arg3 hasProcessView:(char)arg4 total:(SCD_Struct_FP0*)arg5 ;
-(void)printProcessAuxData:(id)arg1 ;
-(void)printProcessesWithWarnings:(id)arg1 processesWithErrors:(id)arg2 globalErrors:(id)arg3 ;
-(void)printGlobalAuxData:(id)arg1 ;
-(void)endAtTime:(id)arg1 ;
-(void)printVmmapLikeOutputForProcess:(id)arg1 regions:(id)arg2 ;
-(void)setProcesses:(NSMutableArray *)arg1 ;
-(NSMutableSet *)addedProcessGroups;
-(void)setAddedProcessGroups:(NSMutableSet *)arg1 ;
-(char)isPageSizeSet;
-(void)setIsPageSizeSet:(char)arg1 ;
@end

