/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:53:01 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libodmodule.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libodmodule.dylib/OS_odx_object.h>
#import <libobjc.A.dylib/OS_odx_module.h>

@protocol OS_odx_module <OS_odx_object>
@end


@class NSString;

@interface OS_odx_module : OS_odx_object <OS_odx_module>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@end

