/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:53:01 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/ssh-keychain.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData;

@interface KPCertificate : NSObject {

	id _privateKey;
	id _privateKeyAcl;
	NSData* _modulus;
	NSData* _exponent;
	NSData* _objId;
	NSData* _subject;
	NSData* _certificateData;
	unsigned long long _keyType;

}

@property (retain) id privateKey;                           //@synthesize privateKey=_privateKey - In the implementation block
@property (retain) id privateKeyAcl;                        //@synthesize privateKeyAcl=_privateKeyAcl - In the implementation block
@property (retain) NSData * modulus;                        //@synthesize modulus=_modulus - In the implementation block
@property (retain) NSData * exponent;                       //@synthesize exponent=_exponent - In the implementation block
@property (retain) NSData * objId;                          //@synthesize objId=_objId - In the implementation block
@property (retain) NSData * subject;                        //@synthesize subject=_subject - In the implementation block
@property (retain) NSData * certificateData;                //@synthesize certificateData=_certificateData - In the implementation block
@property (assign) unsigned long long keyType;              //@synthesize keyType=_keyType - In the implementation block
-(unsigned long long)keyType;
-(void)setSubject:(NSData *)arg1 ;
-(NSData *)subject;
-(id)privateKey;
-(NSData *)exponent;
-(void)setExponent:(NSData *)arg1 ;
-(void)setCertificateData:(NSData *)arg1 ;
-(NSData *)certificateData;
-(void)setKeyType:(unsigned long long)arg1 ;
-(void)setPrivateKey:(id)arg1 ;
-(id)privateKeyAcl;
-(void)setPrivateKeyAcl:(id)arg1 ;
-(NSData *)modulus;
-(void)setModulus:(NSData *)arg1 ;
-(NSData *)objId;
-(void)setObjId:(NSData *)arg1 ;
@end

