/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:05 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libprequelite.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_os_transaction, OS_dispatch_source, OS_dispatch_queue;
#import <libprequelite.dylib/libprequelite.dylib-Structs.h>
@class NSObject, NSMutableArray, NSString, NSURL, NSError;

@interface PQLConnection : NSObject {

	unsigned long long _currentStmtStart;
	sqlite3Ref _db;
	NSObject*<OS_os_transaction> _batchStarted;
	int _suspendCaching;
	int _savePointLevel;
	int _skipBatchStop;
	int _vacuumTracker;
	NSMutableArray* _flushNotifications;
	/*^block*/id _batchingPolicyHandler;
	NSObject*<OS_dispatch_source> _batchingTimer;
	double _batchingPeriod;
	int _batchingChangesLimit;
	int _batchingChangesCount;
	int _cacheSize;
	char _useBatching;
	char _useQueue;
	char _needsFullSync;
	cache_sRef _preparedStatements;
	NSObject*<OS_dispatch_source> _stmtCacheSource;
	NSMutableArray* _stmtCacheCleanupQueue;
	long long _changesOverride;
	NSObject*<OS_dispatch_queue> _targetQueue;
	char _traced;
	char _crashIfUsedAfterClose;
	char _shouldUseWALJournalMode;
	int _batchTransactionType;
	NSString* _label;
	NSURL* _url;
	/*^block*/id _lockedHandler;
	/*^block*/id _busyHandler;
	/*^block*/id _autoRollbackHandler;
	/*^block*/id _sqliteErrorHandler;
	/*^block*/id _preFlushHook;
	/*^block*/id _postFlushHook;
	/*^block*/id _profilingHook;
	/*^block*/id _willBeginBatchingHook;
	/*^block*/id _didFinishBatchingHook;
	NSObject*<OS_dispatch_queue> _serialQueue;
	NSError* _lastError;

}

@property (nonatomic,copy) NSString * label;                                          //@synthesize label=_label - In the implementation block
@property (assign,getter=isTraced,nonatomic) char traced;                             //@synthesize traced=_traced - In the implementation block
@property (assign,nonatomic) char crashIfUsedAfterClose;                              //@synthesize crashIfUsedAfterClose=_crashIfUsedAfterClose - In the implementation block
@property (nonatomic,copy,readonly) NSURL * url;                                      //@synthesize url=_url - In the implementation block
@property (nonatomic,readonly) sqlite3Ref dbHandle;                                   //@synthesize db=_db - In the implementation block
@property (nonatomic,readonly) char isInBatch; 
@property (nonatomic,readonly) char isInTransaction; 
@property (nonatomic,retain) NSError * lastError;                                     //@synthesize lastError=_lastError - In the implementation block
@property (nonatomic,readonly) long long lastInsertedRowID; 
@property (nonatomic,readonly) long long changes; 
@property (assign,nonatomic) unsigned long long statementCacheMaxCount; 
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> serialQueue;              //@synthesize serialQueue=_serialQueue - In the implementation block
@property (nonatomic,readonly) double currentOperationDuration; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) unsigned long long synchronousMode; 
@property (assign,nonatomic) int batchTransactionType;                                //@synthesize batchTransactionType=_batchTransactionType - In the implementation block
@property (assign,nonatomic) char shouldUseWALJournalMode;                            //@synthesize shouldUseWALJournalMode=_shouldUseWALJournalMode - In the implementation block
@property (nonatomic,copy) id lockedHandler;                                          //@synthesize lockedHandler=_lockedHandler - In the implementation block
@property (nonatomic,copy) id busyHandler;                                            //@synthesize busyHandler=_busyHandler - In the implementation block
@property (nonatomic,copy) id autoRollbackHandler;                                    //@synthesize autoRollbackHandler=_autoRollbackHandler - In the implementation block
@property (nonatomic,copy) id sqliteErrorHandler;                                     //@synthesize sqliteErrorHandler=_sqliteErrorHandler - In the implementation block
@property (nonatomic,copy) id preFlushHook;                                           //@synthesize preFlushHook=_preFlushHook - In the implementation block
@property (nonatomic,copy) id postFlushHook;                                          //@synthesize postFlushHook=_postFlushHook - In the implementation block
@property (nonatomic,copy) id profilingHook;                                          //@synthesize profilingHook=_profilingHook - In the implementation block
@property (nonatomic,copy) id willBeginBatchingHook;                                  //@synthesize willBeginBatchingHook=_willBeginBatchingHook - In the implementation block
@property (nonatomic,copy) id didFinishBatchingHook;                                  //@synthesize didFinishBatchingHook=_didFinishBatchingHook - In the implementation block
@property (nonatomic,readonly) char isBatchSuspended; 
+(void)initialize;
-(id)numberWithSQL:(id)arg1 ;
-(char)registerFunction:(id)arg1 nArgs:(int)arg2 handler:(/*^block*/id)arg3 error:(id*)arg4 ;
-(id)stringWithSQL:(id)arg1 ;
-(id)itemIDWithSQL:(id)arg1 ;
-(void)dealloc;
-(id)description;
-(NSString *)debugDescription;
-(id)init;
-(NSObject*<OS_dispatch_queue>)serialQueue;
-(NSURL *)url;
-(NSString *)label;
-(void)setLabel:(NSString *)arg1 ;
-(long long)changes;
-(char)close:(id*)arg1 ;
-(id)userVersion;
-(char)setUserVersion:(long long)arg1 ;
-(unsigned long long)synchronousMode;
-(void)setSynchronousMode:(unsigned long long)arg1 ;
-(void)setTraced:(char)arg1 ;
-(void)flush;
-(id)fetch:(id)arg1 ;
-(char)execute:(id)arg1 ;
-(void)setLastError:(NSError *)arg1 ;
-(NSError *)lastError;
-(void)_resetState;
-(void)assertOnQueue;
-(char)performWithFlags:(unsigned)arg1 action:(/*^block*/id)arg2 ;
-(void)setCrashIfUsedAfterClose:(char)arg1 ;
-(void)setSqliteErrorHandler:(id)arg1 ;
-(double)currentOperationDuration;
-(void)setLockedHandler:(id)arg1 ;
-(char)openAtURL:(id)arg1 withFlags:(int)arg2 error:(id*)arg3 ;
-(char)setupPragmas;
-(id)profilingHook;
-(void)setProfilingHook:(id)arg1 ;
-(char)executeRaw:(id)arg1 ;
-(char)isInTransaction;
-(void)forceBatchStart;
-(id)fetch:(id)arg1 args:(_va_list_tag*)arg2 ;
-(id)fetchObjectOfClass:(Class)arg1 sql:(id)arg2 args:(_va_list_tag*)arg3 ;
-(char)execute:(id)arg1 args:(_va_list_tag*)arg2 ;
-(id)sqliteErrorHandler;
-(void)useBatchingOnTargetQueue:(id)arg1 withPolicyHandler:(/*^block*/id)arg2 ;
-(long long)autovacuumableSpaceInBytes;
-(char)incrementalVacuum:(long long)arg1 ;
-(id)lockedHandler;
-(char)groupInTransaction:(/*^block*/id)arg1 ;
-(void)groupInBatch:(/*^block*/id)arg1 ;
-(char)isBatchSuspended;
-(void)useSerialQueueWithTarget:(id)arg1 ;
-(void)setStatementCacheMaxCount:(unsigned long long)arg1 ;
-(char)registerFunction:(id)arg1 nArgs:(int)arg2 handler:(/*^block*/id)arg3 ;
-(long long)lastInsertedRowID;
-(id)fetchObject:(/*^block*/id)arg1 sql:(id)arg2 ;
-(id)fetchObjectOfClass:(Class)arg1 sql:(id)arg2 ;
-(void)setPreFlushHook:(id)arg1 ;
-(void)setPostFlushHook:(id)arg1 ;
-(id)autoRollbackHandler;
-(void)setAutoRollbackHandler:(id)arg1 ;
-(sqlite3Ref)dbHandle;
-(char)backupToURL:(id)arg1 progress:(/*^block*/id)arg2 ;
-(char)performWithFlags:(unsigned)arg1 action:(/*^block*/id)arg2 whenFlushed:(/*^block*/id)arg3 ;
-(void)useBatchingWithDelay:(double)arg1 changeCount:(int)arg2 ;
-(void)makeNextFlushFullSync;
-(void)useSerialQueue;
-(char)openAtURL:(id)arg1 sharedCache:(char)arg2 error:(id*)arg3 ;
-(void)setBusyHandler:(id)arg1 ;
-(id)_description:(char)arg1 ;
-(void)_clearStatementCache;
-(void)_createCacheIfNeeded;
-(void)_clearCleanupCacheQueueIfNeeded;
-(void)useBatchingOnTargetQueue:(id)arg1 delay:(double)arg2 changeCount:(int)arg3 ;
-(char)_execute:(id)arg1 mustSucceed:(char)arg2 bindings:(_va_list_tag*)arg3 ;
-(int)_vacuumMode;
-(char)_incrementalVacuum:(unsigned long long)arg1 ;
-(char)_fullSync;
-(void)_vacuumIfNeeded;
-(char)_performWithFlags:(unsigned)arg1 action:(/*^block*/id)arg2 whenFlushed:(/*^block*/id)arg3 ;
-(id)_newStatementForFormat:(id)arg1 arguments:(_va_list_tag*)arg2 ;
-(char)_executeStmt:(id)arg1 mustSucceed:(char)arg2 ;
-(id)fetchObjectOfClass:(Class)arg1 initializer:(SEL)arg2 sql:(id)arg3 args:(_va_list_tag*)arg4 ;
-(unsigned long long)statementCacheMaxCount;
-(void)useBatchingWithPolicyHandler:(/*^block*/id)arg1 ;
-(void)_batchStartIfNeeded:(int)arg1 ;
-(void)_batchStopIfNeeded;
-(void)_fireFlushNotifications;
-(char)destroyDatabaseWithError:(id*)arg1 ;
-(char)isInBatch;
-(void)setBatchTransactionType:(int)arg1 ;
-(id)fetchObjectOfClass:(Class)arg1 initializer:(SEL)arg2 sql:(id)arg3 ;
-(id)fetchObject:(/*^block*/id)arg1 sql:(id)arg2 args:(_va_list_tag*)arg3 ;
-(id)busyHandler;
-(id)preFlushHook;
-(id)postFlushHook;
-(id)willBeginBatchingHook;
-(void)setWillBeginBatchingHook:(id)arg1 ;
-(id)didFinishBatchingHook;
-(void)setDidFinishBatchingHook:(id)arg1 ;
-(char)isTraced;
-(char)crashIfUsedAfterClose;
-(int)batchTransactionType;
-(char)shouldUseWALJournalMode;
-(void)setShouldUseWALJournalMode:(char)arg1 ;
-(id)_newStatementForBuilder:(/*^block*/id)arg1 ;
-(char)executeSwift:(/*^block*/id)arg1 error:(id*)arg2 ;
-(id)fetchSwift:(/*^block*/id)arg1 error:(id*)arg2 ;
-(id)fetchObjectOfClassSwift:(Class)arg1 query:(/*^block*/id)arg2 error:(id*)arg3 ;
-(id)fetchObjectSwift:(/*^block*/id)arg1 query:(/*^block*/id)arg2 error:(id*)arg3 ;
@end

