/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:08 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libAudioStatistics.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, NSMutableDictionary, NSDate, CAReportingPerformanceObject;

@interface CAReporter : NSObject {

	char _started;
	char _removedByClient;
	char _connected;
	unsigned short _serviceType;
	NSDictionary* _configuration;
	NSMutableDictionary* _internalConfiguration;
	long long _reporterID;
	NSDate* _startDate;
	CAReportingPerformanceObject* _perfObject;
	unsigned long long _signpostID;

}

@property (retain) NSMutableDictionary * internalConfiguration;              //@synthesize internalConfiguration=_internalConfiguration - In the implementation block
@property (retain) NSDate * startDate;                                       //@synthesize startDate=_startDate - In the implementation block
@property (assign,nonatomic) unsigned short serviceType;                     //@synthesize serviceType=_serviceType - In the implementation block
@property (assign) char started;                                             //@synthesize started=_started - In the implementation block
@property (assign) char removedByClient;                                     //@synthesize removedByClient=_removedByClient - In the implementation block
@property (assign) char connected;                                           //@synthesize connected=_connected - In the implementation block
@property (retain) CAReportingPerformanceObject * perfObject;                //@synthesize perfObject=_perfObject - In the implementation block
@property (readonly) unsigned long long signpostID;                          //@synthesize signpostID=_signpostID - In the implementation block
@property (readonly) long long reporterID;                                   //@synthesize reporterID=_reporterID - In the implementation block
@property (nonatomic,retain) NSDictionary * configuration;                   //@synthesize configuration=_configuration - In the implementation block
+(void)sendSingleMessage:(id)arg1 category:(unsigned)arg2 type:(unsigned short)arg3 ;
-(void)dealloc;
-(void)start;
-(char)started;
-(void)stop;
-(NSDate *)startDate;
-(NSDictionary *)configuration;
-(void)setConfiguration:(NSDictionary *)arg1 ;
-(unsigned short)serviceType;
-(void)setStartDate:(NSDate *)arg1 ;
-(char)connected;
-(void)setConnected:(char)arg1 ;
-(void)setServiceType:(unsigned short)arg1 ;
-(void)setStarted:(char)arg1 ;
-(id)initWithNewReporterID;
-(void)sendMessage:(id)arg1 category:(unsigned)arg2 type:(unsigned short)arg3 ;
-(long long)reporterID;
-(id)initWithSessionID:(unsigned)arg1 serviceType:(unsigned short)arg2 ;
-(CAReportingPerformanceObject *)perfObject;
-(id)initWithReporterID:(long long)arg1 serviceType:(unsigned short)arg2 ;
-(void)updateWithReporterID:(long long)arg1 ;
-(void)cacheServiceType:(unsigned short)arg1 ;
-(NSMutableDictionary *)internalConfiguration;
-(void)setInternalConfiguration:(NSMutableDictionary *)arg1 ;
-(char)removedByClient;
-(void)setRemovedByClient:(char)arg1 ;
-(void)setPerfObject:(CAReportingPerformanceObject *)arg1 ;
-(unsigned long long)signpostID;
@end

