/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:08 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libAudioStatistics.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libAudioStatistics.dylib/libAudioStatistics.dylib-Structs.h>
@class NSDictionary, NSString, NSArray;

@interface CAReportingPerformanceObject : NSObject {

	unsigned short _serviceType;
	NSDictionary* _performanceMetrics;
	NSDictionary* _configuration;
	NSString* _perfDataPath;
	NSString* _perfDataName;
	pc_sessionRef _session;
	NSArray* _processIdentifiers;

}

@property (retain) NSString * perfDataPath;                                    //@synthesize perfDataPath=_perfDataPath - In the implementation block
@property (retain) NSString * perfDataName;                                    //@synthesize perfDataName=_perfDataName - In the implementation block
@property (assign) pc_sessionRef session;                                      //@synthesize session=_session - In the implementation block
@property (retain) NSArray * processIdentifiers;                               //@synthesize processIdentifiers=_processIdentifiers - In the implementation block
@property (nonatomic,readonly) NSDictionary * performanceMetrics;              //@synthesize performanceMetrics=_performanceMetrics - In the implementation block
@property (assign,nonatomic) unsigned short serviceType;                       //@synthesize serviceType=_serviceType - In the implementation block
@property (nonatomic,retain) NSDictionary * configuration;                     //@synthesize configuration=_configuration - In the implementation block
-(void)begin;
-(NSDictionary *)configuration;
-(pc_sessionRef)session;
-(void)setConfiguration:(NSDictionary *)arg1 ;
-(unsigned short)serviceType;
-(void)setSession:(pc_sessionRef)arg1 ;
-(void)setServiceType:(unsigned short)arg1 ;
-(void)setProcessIdentifiers:(NSArray *)arg1 ;
-(NSArray *)processIdentifiers;
-(void)setPerfDataName:(NSString *)arg1 ;
-(id)initWithProcessIdentifiers:(id)arg1 ;
-(id)endAndReturnPerformanceMetrics;
-(NSDictionary *)performanceMetrics;
-(NSString *)perfDataPath;
-(void)setPerfDataPath:(NSString *)arg1 ;
-(NSString *)perfDataName;
@end

