/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:30 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libAppleSSEExt.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface BAASupport : NSObject
+(void)initialize;
+(void)setDelegate:(id)arg1 ;
+(int)prepare;
+(void)setBlessedUser:(unsigned)arg1 keybagUUID:(unsigned char)arg2 ;
+(int)getCertificateExpirationDate:(double*)arg1 ;
+(int)getCertificates:(id*)arg1 ;
+(int)issueNewCertificate;
@end

