/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray;

@interface RTAccount : NSObject {

	char _primaryEmailVerified;
	NSString* _dsid;
	NSString* _firstName;
	NSString* _lastName;
	NSString* _appleID;
	NSString* _altDSID;
	NSString* _primaryEmail;
	NSString* _appleIDAlias;
	NSArray* _appleIDAliases;

}

@property (nonatomic,retain) NSString * dsid;                        //@synthesize dsid=_dsid - In the implementation block
@property (nonatomic,retain) NSString * firstName;                   //@synthesize firstName=_firstName - In the implementation block
@property (nonatomic,retain) NSString * lastName;                    //@synthesize lastName=_lastName - In the implementation block
@property (assign,nonatomic) char primaryEmailVerified;              //@synthesize primaryEmailVerified=_primaryEmailVerified - In the implementation block
@property (nonatomic,retain) NSString * appleID;                     //@synthesize appleID=_appleID - In the implementation block
@property (nonatomic,retain) NSString * altDSID;                     //@synthesize altDSID=_altDSID - In the implementation block
@property (nonatomic,retain) NSString * primaryEmail;                //@synthesize primaryEmail=_primaryEmail - In the implementation block
@property (nonatomic,retain) NSString * appleIDAlias;                //@synthesize appleIDAlias=_appleIDAlias - In the implementation block
@property (nonatomic,retain) NSArray * appleIDAliases;               //@synthesize appleIDAliases=_appleIDAliases - In the implementation block
-(id)description;
-(id)init;
-(NSString *)dsid;
-(void)setDsid:(NSString *)arg1 ;
-(NSString *)altDSID;
-(void)setAltDSID:(NSString *)arg1 ;
-(NSString *)firstName;
-(NSString *)lastName;
-(NSString *)appleID;
-(void)setAppleID:(NSString *)arg1 ;
-(id)appleIDs;
-(id)initWithACAccount:(id)arg1 ;
-(void)setFirstName:(NSString *)arg1 ;
-(void)setLastName:(NSString *)arg1 ;
-(void)setPrimaryEmailVerified:(char)arg1 ;
-(void)setPrimaryEmail:(NSString *)arg1 ;
-(void)setAppleIDAlias:(NSString *)arg1 ;
-(void)setAppleIDAliases:(NSArray *)arg1 ;
-(char)primaryEmailVerified;
-(NSString *)primaryEmail;
-(NSString *)appleIDAlias;
-(NSArray *)appleIDAliases;
@end

