/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTAuthorizationManagerNotificationConsoleUserDidChange : RTNotification {

	char _activeUser;

}

@property (getter=activeUser,nonatomic,readonly) char activeUser;              //@synthesize activeUser=_activeUser - In the implementation block
-(id)init;
-(id)initWithactiveUser:(char)arg1 ;
-(char)activeUser;
@end

