/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
#import <libcoreroutine.dylib/RTService.h>

@class RTInvocationDispatcher, RTPlatform, RTUserSessionMonitor;

@interface RTAuthorizationManager : RTService {

	char _supported;
	char _enabled;
	char _ready;
	RTInvocationDispatcher* _dispatcher;
	RTPlatform* _platform;
	RTUserSessionMonitor* _userSessionMonitor;

}

@property (nonatomic,retain) RTInvocationDispatcher * dispatcher;              //@synthesize dispatcher=_dispatcher - In the implementation block
@property (assign,getter=isSupported,nonatomic) char supported;                //@synthesize supported=_supported - In the implementation block
@property (assign,getter=isEnabled,nonatomic) char enabled;                    //@synthesize enabled=_enabled - In the implementation block
@property (assign,getter=isReady,nonatomic) char ready;                        //@synthesize ready=_ready - In the implementation block
@property (nonatomic,retain) RTPlatform * platform;                            //@synthesize platform=_platform - In the implementation block
@property (retain) RTUserSessionMonitor * userSessionMonitor;                  //@synthesize userSessionMonitor=_userSessionMonitor - In the implementation block
+(id)allocWithZone:(NSZone*)arg1 ;
+(char)supportsNotificationName:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setEnabled:(char)arg1 ;
-(char)isEnabled;
-(RTPlatform *)platform;
-(char)isReady;
-(void)setPlatform:(RTPlatform *)arg1 ;
-(void)_setup;
-(void)setSupported:(char)arg1 ;
-(char)isLocationServicesEnabled;
-(id)initWithPlatform:(id)arg1 userSessionMonitor:(id)arg2 ;
-(void)onUserSessionChangeNotification:(id)arg1 ;
-(char)isCoreRoutineLocationClientEnabled;
-(void)setup;
-(RTInvocationDispatcher *)dispatcher;
-(char)isSupported;
-(RTUserSessionMonitor *)userSessionMonitor;
-(void)_shutdown;
-(void)fetchRoutineEnabledWithHandler:(/*^block*/id)arg1 ;
-(void)fetchRoutineSupportedWithHandler:(/*^block*/id)arg1 ;
-(char)shouldPersistLocations;
-(void)setRoutineEnabled:(char)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)updateRoutineEnabled:(char)arg1 ;
-(void)handleAppResetChangeNotification;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)setDispatcher:(RTInvocationDispatcher *)arg1 ;
-(void)setReady:(char)arg1 ;
-(void)setUserSessionMonitor:(RTUserSessionMonitor *)arg1 ;
@end

