/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTCameraManagerNotificationCameraPowerChanged : RTNotification {

	long long _powerState;
	long long _cameraType;

}

@property (nonatomic,readonly) long long powerState;              //@synthesize powerState=_powerState - In the implementation block
@property (nonatomic,readonly) long long cameraType;              //@synthesize cameraType=_cameraType - In the implementation block
-(long long)powerState;
-(id)initWithCameraType:(long long)arg1 powerState:(long long)arg2 ;
-(long long)cameraType;
@end

