/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTService.h>

@class RTDataProtectionManager, RTMapServiceManager, RTDistanceCalculator, CNContact;

@interface RTContactsManager : RTService {

	char _available;
	RTDataProtectionManager* _dataProtectionManager;
	RTMapServiceManager* _mapServiceManager;
	RTDistanceCalculator* _distanceCalculator;
	CNContact* _meCard;

}

@property (nonatomic,retain) RTDataProtectionManager * dataProtectionManager;              //@synthesize dataProtectionManager=_dataProtectionManager - In the implementation block
@property (nonatomic,retain) RTMapServiceManager * mapServiceManager;                      //@synthesize mapServiceManager=_mapServiceManager - In the implementation block
@property (nonatomic,retain) RTDistanceCalculator * distanceCalculator;                    //@synthesize distanceCalculator=_distanceCalculator - In the implementation block
@property (nonatomic,retain) CNContact * meCard;                                           //@synthesize meCard=_meCard - In the implementation block
@property (assign,nonatomic) char available;                                               //@synthesize available=_available - In the implementation block
+(id)addressLabelTypeToString:(unsigned long long)arg1 ;
+(unsigned long long)labelStringToAddressLabelType:(id)arg1 ;
+(id)addressDictionaryFromMapItem:(id)arg1 ;
+(id)addressLabelTypeToLabel:(unsigned long long)arg1 ;
+(id)formattedPostalAddressesForContact:(id)arg1 ;
-(id)init;
-(void)_setup;
-(char)available;
-(void)setAvailable:(char)arg1 ;
-(void)_shutdown;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)fetchFormattedPostalAddressesFromMeCard:(/*^block*/id)arg1 ;
-(RTMapServiceManager *)mapServiceManager;
-(void)setMapServiceManager:(RTMapServiceManager *)arg1 ;
-(RTDistanceCalculator *)distanceCalculator;
-(id)initWithDataProtectionManager:(id)arg1 mapServiceManager:(id)arg2 distanceCalculator:(id)arg3 ;
-(id)addressIdentifierOfMeCardWithAddressFromMapItem:(id)arg1 error:(id*)arg2 ;
-(char)updateAddressOfMeCardWithAddressIdentifier:(id)arg1 toAddressFromMapItem:(id)arg2 error:(id*)arg3 ;
-(char)updateAddressLabelTypeOfMeCardWithAddressIdentifier:(id)arg1 toAddressLabelType:(unsigned long long)arg2 error:(id*)arg3 ;
-(char)removeAddressOfMeCardWithAddressIdentifier:(id)arg1 error:(id*)arg2 ;
-(id)addAddressToMeCardWithAddressLabelType:(unsigned long long)arg1 addressFromMapItem:(id)arg2 error:(id*)arg3 ;
-(void)fetchMeCardWithHandler:(/*^block*/id)arg1 ;
-(void)setDistanceCalculator:(RTDistanceCalculator *)arg1 ;
-(RTDataProtectionManager *)dataProtectionManager;
-(void)donateAddressFromMapItem:(id)arg1 addressLabelType:(unsigned long long)arg2 handler:(/*^block*/id)arg3 ;
-(void)onDataProtectionNotification:(id)arg1 ;
-(void)onContactStoreNotification:(id)arg1 ;
-(void)_onContactStoreNotification:(id)arg1 ;
-(id)_getMeCardWithError:(id*)arg1 ;
-(CNContact *)meCard;
-(void)setMeCard:(CNContact *)arg1 ;
-(void)_fetchMeCardWithHandler:(/*^block*/id)arg1 ;
-(char)labelTypeValidForDonation:(unsigned long long)arg1 ;
-(void)__donateAddressFromMapItem:(id)arg1 addressLabelType:(unsigned long long)arg2 donationStore:(id)arg3 handler:(/*^block*/id)arg4 ;
-(void)_donateAddressFromMapItem:(id)arg1 addressLabelType:(unsigned long long)arg2 handler:(/*^block*/id)arg3 ;
-(char)removeAddressOfContact:(id)arg1 withAddressIdentifier:(id)arg2 error:(id*)arg3 ;
-(id)addressIdentifierOfContact:(id)arg1 withAddressFromMapItem:(id)arg2 error:(id*)arg3 ;
-(id)addAddressToContact:(id)arg1 addressLabelType:(unsigned long long)arg2 addressFromMapItem:(id)arg3 error:(id*)arg4 ;
-(char)updateAddressOfContact:(id)arg1 withAddressIdentifier:(id)arg2 toAddressFromMapItem:(id)arg3 error:(id*)arg4 ;
-(char)updateAddressLabelTypeOfContact:(id)arg1 withAddressIdentifier:(id)arg2 toAddressLabelType:(unsigned long long)arg3 error:(id*)arg4 ;
-(void)setDataProtectionManager:(RTDataProtectionManager *)arg1 ;
@end

