/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSUUID, NSNumber, NSDate, NSSet;

@interface RTFingerprintMO : NSManagedObject

@property (nonatomic,copy) NSUUID * identifier; 
@property (nonatomic,copy) NSNumber * settledState; 
@property (nonatomic,copy) NSDate * start; 
@property (nonatomic,retain) NSSet * wifiAccessPoints; 
+(id)fetchRequest;
+(id)fetchLastByStartDateInManagedObjectContext:(id)arg1 error:(id*)arg2 ;
+(id)managedObjectWithFingerprint:(id)arg1 inManagedObjectContext:(id)arg2 ;
@end

