/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTMapItem;

@interface RTFusedInferredMapItem : NSObject {

	RTMapItem* _mapItem;
	double _confidence;
	unsigned long long _source;

}

@property (nonatomic,retain) RTMapItem * mapItem;                    //@synthesize mapItem=_mapItem - In the implementation block
@property (assign,nonatomic) double confidence;                      //@synthesize confidence=_confidence - In the implementation block
@property (assign,nonatomic) unsigned long long source;              //@synthesize source=_source - In the implementation block
+(id)sortFusedInferredMapItems:(id)arg1 confidenceEqualityEpsilon:(double)arg2 referenceLocation:(id)arg3 distanceCalculator:(id)arg4 ascending:(char)arg5 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)init;
-(unsigned long long)source;
-(double)confidence;
-(void)setSource:(unsigned long long)arg1 ;
-(void)setConfidence:(double)arg1 ;
-(RTMapItem *)mapItem;
-(id)convertToInferredMapItem;
-(void)setMapItem:(RTMapItem *)arg1 ;
-(id)initWithMapItem:(id)arg1 confidence:(double)arg2 source:(unsigned long long)arg3 ;
-(id)initWithInferredMapItem:(id)arg1 ;
@end

