/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject;

@interface RTLifeCycleManager : NSObject {

	NSMutableArray* _signals;
	NSMutableDictionary* _listeners;
	NSMutableSet* _services;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) NSMutableArray * signals;                        //@synthesize signals=_signals - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * listeners;                 //@synthesize listeners=_listeners - In the implementation block
@property (nonatomic,retain) NSMutableSet * services;                         //@synthesize services=_services - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
-(void)dealloc;
-(id)init;
-(NSMutableSet *)services;
-(void)start;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)exit;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)_start;
-(void)addService:(id)arg1 ;
-(void)submitUptimeMetricsWithDefaultsMananger:(id)arg1 ;
-(NSMutableArray *)signals;
-(id)createSourceForSignal:(int)arg1 withBlock:(/*^block*/id)arg2 ;
-(void)_exit;
-(id)serviceWithClass:(Class)arg1 ;
-(NSMutableDictionary *)listeners;
-(void)exitWithDelay:(double)arg1 ;
-(void)setSignals:(NSMutableArray *)arg1 ;
-(void)setListeners:(NSMutableDictionary *)arg1 ;
-(void)setServices:(NSMutableSet *)arg1 ;
@end

