/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTLocationStoreMetrics : NSObject {

	unsigned long long _count;
	double _distanceTraveled;
	double _maxIntervalBetweenLocations;
	double _spread;

}

@property (assign,nonatomic) unsigned long long count;                        //@synthesize count=_count - In the implementation block
@property (assign,nonatomic) double distanceTraveled;                         //@synthesize distanceTraveled=_distanceTraveled - In the implementation block
@property (assign,nonatomic) double maxIntervalBetweenLocations;              //@synthesize maxIntervalBetweenLocations=_maxIntervalBetweenLocations - In the implementation block
@property (assign,nonatomic) double spread;                                   //@synthesize spread=_spread - In the implementation block
-(id)description;
-(id)init;
-(unsigned long long)count;
-(void)setCount:(unsigned long long)arg1 ;
-(id)initWithCount:(unsigned long long)arg1 maxIntervalBetweenLocations:(double)arg2 spread:(double)arg3 distanceTraveled:(double)arg4 ;
-(double)distanceTraveled;
-(void)setDistanceTraveled:(double)arg1 ;
-(double)maxIntervalBetweenLocations;
-(void)setMaxIntervalBetweenLocations:(double)arg1 ;
-(double)spread;
-(void)setSpread:(double)arg1 ;
@end

