/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTMapItemProviderPortraitParameters : NSObject {

	double _confidence;

}

@property (nonatomic,readonly) double confidence;              //@synthesize confidence=_confidence - In the implementation block
-(id)description;
-(id)init;
-(double)confidence;
-(id)initWithDefaultsManager:(id)arg1 ;
-(id)initWithConfidence:(double)arg1 ;
@end

