/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
#import <libobjc.A.dylib/RTMetricProtocol.h>

@class NSMutableDictionary, NSString;

@interface RTMetric : NSObject <RTMetricProtocol> {

	char _loggingEnabled;
	char _submitted;
	NSMutableDictionary* _metrics;

}

@property (assign,nonatomic) char loggingEnabled;                          //@synthesize loggingEnabled=_loggingEnabled - In the implementation block
@property (assign,nonatomic) char submitted;                               //@synthesize submitted=_submitted - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * metrics;              //@synthesize metrics=_metrics - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(SCD_Struct_RT3)event;
+(id)binForNumber:(id)arg1 bins:(id)arg2 ;
+(id)supportedMetricKeys;
+(id)binsFromStart:(id)arg1 toEnd:(id)arg2 gap:(id)arg3 ;
+(id)metricName;
-(NSString *)description;
-(id)init;
-(NSMutableDictionary *)metrics;
-(char)submitMetricsWithError:(id*)arg1 ;
-(char)setAllMetrics:(id)arg1 error:(id*)arg2 ;
-(id)initWithLoggingEnabled:(char)arg1 ;
-(char)loggingEnabled;
-(void)setLoggingEnabled:(char)arg1 ;
-(char)submitted;
-(void)setSubmitted:(char)arg1 ;
@end

