/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTNextPredictedLocationsOfInterestCacheDelegate, OS_dispatch_queue;
@class NSObject, NSArray, RTDataProtectionManager, RTStarkManager;

@interface RTNextPredictedLocationsOfInterestCache : NSObject {

	char _enabled;
	id<RTNextPredictedLocationsOfInterestCacheDelegate> _delegate;
	NSObject*<OS_dispatch_queue> _queue;
	NSArray* _nextPredictedLocationsOfInterest;
	RTDataProtectionManager* _dataProtectionManager;
	RTStarkManager* _starkManager;

}

@property (assign,nonatomic) char enabled;                                                                     //@synthesize enabled=_enabled - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                                               //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSArray * nextPredictedLocationsOfInterest;                                       //@synthesize nextPredictedLocationsOfInterest=_nextPredictedLocationsOfInterest - In the implementation block
@property (nonatomic,retain) RTDataProtectionManager * dataProtectionManager;                                  //@synthesize dataProtectionManager=_dataProtectionManager - In the implementation block
@property (nonatomic,retain) RTStarkManager * starkManager;                                                    //@synthesize starkManager=_starkManager - In the implementation block
@property (assign,nonatomic,__weak) id<RTNextPredictedLocationsOfInterestCacheDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)cachePath;
-(void)dealloc;
-(id)init;
-(id<RTNextPredictedLocationsOfInterestCacheDelegate>)delegate;
-(void)setDelegate:(id<RTNextPredictedLocationsOfInterestCacheDelegate>)arg1 ;
-(char)enabled;
-(void)setEnabled:(char)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)clear;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)initWithQueue:(id)arg1 dataProtectionManager:(id)arg2 starkManager:(id)arg3 ;
-(RTDataProtectionManager *)dataProtectionManager;
-(void)purgeWithReferenceDate:(id)arg1 ;
-(NSArray *)nextPredictedLocationsOfInterest;
-(void)setNextPredictedLocationsOfInterest:(NSArray *)arg1 ;
-(void)onDataProtectionNotification:(id)arg1 ;
-(void)setDataProtectionManager:(RTDataProtectionManager *)arg1 ;
-(void)cacheNextPredictedLocationsOfInterest:(id)arg1 ;
-(id)getCachedNextPredictedLocationsOfInterest;
-(void)handleUnlockedSinceBoot:(char)arg1 ;
-(void)onStarkNotification:(id)arg1 ;
-(void)handleStarkTrustedConnectionEstablished:(char)arg1 ;
-(RTStarkManager *)starkManager;
-(void)setStarkManager:(RTStarkManager *)arg1 ;
@end

