/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObjectContext.h>

@protocol RTPersistenceContextDelegate;
@class RTPredicateInspector;

@interface RTPersistenceContext : NSManagedObjectContext {

	long long _mirroringQualityOfService;
	id<RTPersistenceContextDelegate> _delegate;
	RTPredicateInspector* _predicateInspector;
	unsigned long long _options;

}

@property (__weak) id<RTPersistenceContextDelegate> delegate;                        //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) RTPredicateInspector * predicateInspector;              //@synthesize predicateInspector=_predicateInspector - In the implementation block
@property (assign,nonatomic) unsigned long long options;                             //@synthesize options=_options - In the implementation block
@property (assign,nonatomic) long long mirroringQualityOfService;                    //@synthesize mirroringQualityOfService=_mirroringQualityOfService - In the implementation block
-(id<RTPersistenceContextDelegate>)delegate;
-(void)setDelegate:(id<RTPersistenceContextDelegate>)arg1 ;
-(void)setOptions:(unsigned long long)arg1 ;
-(unsigned long long)options;
-(id)executeFetchRequest:(id)arg1 error:(id*)arg2 ;
-(char)save:(id*)arg1 ;
-(id)executeRequest:(id)arg1 error:(id*)arg2 ;
-(unsigned long long)countForFetchRequest:(id)arg1 error:(id*)arg2 ;
-(id)initWithConcurrencyType:(unsigned long long)arg1 ;
-(id)initWithConcurrencyType:(unsigned long long)arg1 options:(unsigned long long)arg2 ;
-(char)validateEntityName:(id)arg1 inModel:(id)arg2 ;
-(char)_shouldExecute:(id*)arg1 ;
-(id)substitutionVariableKeys;
-(char)shouldSubstituteVariables:(id)arg1 inPredicate:(id)arg2 entityName:(id)arg3 model:(id)arg4 ;
-(id)predicateWithDefaultSubstitutionVariables:(id)arg1 ;
-(void)_updateRequest:(id*)arg1 includingContextOptions:(unsigned long long)arg2 ;
-(char)_processError:(inout id*)arg1 ;
-(long long)mirroringQualityOfService;
-(void)setMirroringQualityOfService:(long long)arg1 ;
-(char)allowTombstones;
-(RTPredicateInspector *)predicateInspector;
-(void)setPredicateInspector:(RTPredicateInspector *)arg1 ;
@end

