/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTPersistenceManager;

@interface RTPersistenceExpirationEnforcer : NSObject {

	RTPersistenceManager* _persistenceManager;

}
-(id)init;
-(id)initWithPersistenceManager:(id)arg1 ;
-(id)collectRecordIDsByTypeExpiredBeforeDate:(id)arg1 ownedByThisDevice:(char)arg2 context:(id)arg3 error:(id*)arg4 ;
-(char)removeExpiredRecordsBeforeDate:(id)arg1 context:(id)arg2 error:(id*)arg3 ;
-(id)entitiesWithDeviceAndExpirationProperty:(id)arg1 ownedByThisDevice:(char)arg2 ;
-(id)objectsWithLifetimeMatchingObjectWithID:(id)arg1 context:(id)arg2 error:(id*)arg3 ;
-(void)mergeEntriesFromDictionary:(id)arg1 intoDictionary:(id)arg2 ;
-(id)objectIDsByTypeAffectedByDeletingObjectWithID:(id)arg1 context:(id)arg2 error:(id*)arg3 ;
-(char)removeExpiredRecordsWithObjectIDs:(id)arg1 context:(id)arg2 error:(id*)arg3 ;
-(void)mergeIdentifiersFromArray:(id)arg1 entityName:(id)arg2 intoDictionary:(id)arg3 ;
-(char)repairInvalidExpirationDatesWithContext:(id)arg1 error:(id*)arg2 ;
-(char)removeRecordsOwnedByThisDeviceExpiredBeforeDate:(id)arg1 context:(id)arg2 error:(id*)arg3 ;
-(char)removeRecordsOwnedByOtherDevicesExpiredBeforeDate:(id)arg1 allowPropagation:(char)arg2 context:(id)arg3 error:(id*)arg4 ;
@end

