/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTLocation;

@interface RTPotentialNoiseLocation : NSObject {

	char _isNoise;
	RTLocation* _location;

}

@property (nonatomic,readonly) RTLocation * location;                    //@synthesize location=_location - In the implementation block
@property (assign,setter=setNoise:,nonatomic) char isNoise;              //@synthesize isNoise=_isNoise - In the implementation block
-(RTLocation *)location;
-(id)initWithLocation:(id)arg1 ;
-(char)isNoise;
-(void)setNoise:(char)arg1 ;
@end

