/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSPredicateVisitor.h>

@class NSSet;

@interface RTPredicateInspector : NSObject <NSPredicateVisitor> {

	char _predicateContainsSubstitutionVariables;
	NSSet* _substitutionVariables;

}

@property (assign,nonatomic) char predicateContainsSubstitutionVariables;              //@synthesize predicateContainsSubstitutionVariables=_predicateContainsSubstitutionVariables - In the implementation block
@property (nonatomic,retain) NSSet * substitutionVariables;                            //@synthesize substitutionVariables=_substitutionVariables - In the implementation block
-(void)visitPredicateExpression:(id)arg1 ;
-(void)visitPredicate:(id)arg1 ;
-(void)visitPredicateOperator:(id)arg1 ;
-(char)predicate:(id)arg1 referencesSubstitutionVariablesFromSet:(id)arg2 ;
-(void)_inspectExpression:(id)arg1 ;
-(char)predicateContainsSubstitutionVariables;
-(void)setPredicateContainsSubstitutionVariables:(char)arg1 ;
-(NSSet *)substitutionVariables;
-(void)setSubstitutionVariables:(NSSet *)arg1 ;
@end

