/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSPredicateVisitor.h>

@class NSPredicate, NSSet, NSError;

@interface RTPredicateValidator : NSObject <NSPredicateVisitor> {

	char _validated;
	NSPredicate* _predicate;
	NSSet* _allowedKeys;
	NSError* _error;

}

@property (assign,nonatomic) char validated;                       //@synthesize validated=_validated - In the implementation block
@property (nonatomic,retain) NSPredicate * predicate;              //@synthesize predicate=_predicate - In the implementation block
@property (nonatomic,retain) NSSet * allowedKeys;                  //@synthesize allowedKeys=_allowedKeys - In the implementation block
@property (nonatomic,retain) NSError * error;                      //@synthesize error=_error - In the implementation block
+(char)validatePredicate:(id)arg1 allowedKeys:(id)arg2 error:(id*)arg3 ;
-(NSError *)error;
-(void)setError:(NSError *)arg1 ;
-(NSPredicate *)predicate;
-(void)setPredicate:(NSPredicate *)arg1 ;
-(void)visitPredicateExpression:(id)arg1 ;
-(void)visitPredicate:(id)arg1 ;
-(void)visitPredicateOperator:(id)arg1 ;
-(id)initWithPredicate:(id)arg1 allowedKeys:(id)arg2 ;
-(char)validateWithError:(id*)arg1 ;
-(void)setValidated:(char)arg1 ;
-(NSSet *)allowedKeys;
-(char)validated;
-(void)setAllowedKeys:(NSSet *)arg1 ;
@end

