/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDate, RTLocation;

@interface RTPredictedDatesCriteria : NSObject <NSCopying> {

	NSDate* _referenceDate;
	double _windowDuration;
	RTLocation* _referenceLocation;
	double _minimumConfidence;

}

@property (nonatomic,retain) NSDate * referenceDate;                      //@synthesize referenceDate=_referenceDate - In the implementation block
@property (assign,nonatomic) double windowDuration;                       //@synthesize windowDuration=_windowDuration - In the implementation block
@property (nonatomic,retain) RTLocation * referenceLocation;              //@synthesize referenceLocation=_referenceLocation - In the implementation block
@property (assign,nonatomic) double minimumConfidence;                    //@synthesize minimumConfidence=_minimumConfidence - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)init;
-(NSDate *)referenceDate;
-(void)setReferenceDate:(NSDate *)arg1 ;
-(RTLocation *)referenceLocation;
-(double)windowDuration;
-(void)setWindowDuration:(double)arg1 ;
-(void)setReferenceLocation:(RTLocation *)arg1 ;
-(double)minimumConfidence;
-(void)setMinimumConfidence:(double)arg1 ;
-(char)evaluatePredictedDate:(id)arg1 ;
@end

