/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate;

@interface RTReviewedPlace : NSObject {

	char _hasUserReviewed;
	unsigned long long _muid;
	NSDate* _lastSuggestedReviewDate;
	NSDate* _modifiedDate;

}

@property (nonatomic,readonly) unsigned long long muid;                       //@synthesize muid=_muid - In the implementation block
@property (nonatomic,readonly) NSDate * lastSuggestedReviewDate;              //@synthesize lastSuggestedReviewDate=_lastSuggestedReviewDate - In the implementation block
@property (nonatomic,readonly) char hasUserReviewed;                          //@synthesize hasUserReviewed=_hasUserReviewed - In the implementation block
@property (nonatomic,readonly) NSDate * modifiedDate;                         //@synthesize modifiedDate=_modifiedDate - In the implementation block
-(id)description;
-(id)init;
-(id)initWithMuid:(unsigned long long)arg1 lastSuggestedReviewDate:(id)arg2 hasUserReviewed:(char)arg3 modifiedDate:(id)arg4 ;
-(unsigned long long)muid;
-(NSDate *)lastSuggestedReviewDate;
-(char)hasUserReviewed;
-(NSDate *)modifiedDate;
@end

