/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSMutableArray;

@interface RTStateTransition : NSObject <NSSecureCoding> {

	NSMutableArray* _listTransitions;

}

@property (nonatomic,retain) NSMutableArray * listTransitions;              //@synthesize listTransitions=_listTransitions - In the implementation block
+(char)supportsSecureCoding;
-(id)init;
-(long long)count;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setListTransitions:(NSMutableArray *)arg1 ;
-(NSMutableArray *)listTransitions;
-(void)addStateTransitionOneTimeTransFromStateTransition:(id)arg1 ;
-(void)submitTransition:(id)arg1 ;
-(void)showTransition;
-(void)cleanTransition:(double)arg1 ;
-(id)getPredTrans:(double)arg1 duration:(double)arg2 numOfWeeks:(int)arg3 uniqueID:(id)arg4 ;
@end

