/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTStateModelLocation;

@interface RTStateDepictionAggStateStats : NSObject {

	int _numOfEntries;
	RTStateModelLocation* _location;
	double _aggregateTime_s;
	double _lastExit_s;

}

@property (nonatomic,retain) RTStateModelLocation * location;              //@synthesize location=_location - In the implementation block
@property (assign,nonatomic) double aggregateTime_s;                       //@synthesize aggregateTime_s=_aggregateTime_s - In the implementation block
@property (assign,nonatomic) double lastExit_s;                            //@synthesize lastExit_s=_lastExit_s - In the implementation block
@property (assign,nonatomic) int numOfEntries;                             //@synthesize numOfEntries=_numOfEntries - In the implementation block
-(id)init;
-(RTStateModelLocation *)location;
-(void)setLocation:(RTStateModelLocation *)arg1 ;
-(void)setAggregateTime_s:(double)arg1 ;
-(double)aggregateTime_s;
-(void)setLastExit_s:(double)arg1 ;
-(void)setNumOfEntries:(int)arg1 ;
-(double)lastExit_s;
-(int)numOfEntries;
@end

