/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDateInterval, NSNumber;

@interface RTStoredSettledStateTransitionEnumerationOptions : NSObject {

	char _ascending;
	NSDateInterval* _dateInterval;
	NSNumber* _limit;
	unsigned long long _batchSize;

}

@property (nonatomic,readonly) char ascending;                            //@synthesize ascending=_ascending - In the implementation block
@property (nonatomic,copy) NSDateInterval * dateInterval;                 //@synthesize dateInterval=_dateInterval - In the implementation block
@property (nonatomic,readonly) NSNumber * limit;                          //@synthesize limit=_limit - In the implementation block
@property (nonatomic,readonly) unsigned long long batchSize;              //@synthesize batchSize=_batchSize - In the implementation block
-(id)description;
-(NSNumber *)limit;
-(char)ascending;
-(NSDateInterval *)dateInterval;
-(unsigned long long)batchSize;
-(id)initWithAscending:(char)arg1 dateInterval:(id)arg2 limit:(id)arg3 batchSize:(unsigned long long)arg4 ;
-(void)setDateInterval:(NSDateInterval *)arg1 ;
@end

