/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate;

@interface RTStateModelDateStats : NSObject {

	int _numOfDates;
	NSDate* _averageDate;
	double _stdDeviation;
	double _timeIntervalToLatestDateSum;
	double _timeIntervalToLatestDateSum2;

}

@property (assign,nonatomic) double timeIntervalToLatestDateSum;               //@synthesize timeIntervalToLatestDateSum=_timeIntervalToLatestDateSum - In the implementation block
@property (assign,nonatomic) double timeIntervalToLatestDateSum2;              //@synthesize timeIntervalToLatestDateSum2=_timeIntervalToLatestDateSum2 - In the implementation block
@property (nonatomic,retain) NSDate * averageDate;                             //@synthesize averageDate=_averageDate - In the implementation block
@property (assign,nonatomic) double stdDeviation;                              //@synthesize stdDeviation=_stdDeviation - In the implementation block
@property (assign,nonatomic) int numOfDates;                                   //@synthesize numOfDates=_numOfDates - In the implementation block
-(NSDate *)averageDate;
-(void)setAverageDate:(NSDate *)arg1 ;
-(double)stdDeviation;
-(void)setStdDeviation:(double)arg1 ;
-(int)numOfDates;
-(void)setNumOfDates:(int)arg1 ;
-(double)timeIntervalToLatestDateSum;
-(void)setTimeIntervalToLatestDateSum:(double)arg1 ;
-(double)timeIntervalToLatestDateSum2;
-(void)setTimeIntervalToLatestDateSum2:(double)arg1 ;
@end

