/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTVehicleLocationEstimator : NSObject
-(double)getRefAlt:(id)arg1 ;
-(id)estimateVehicleLocationWithLocations:(id)arg1 parkingTimestamp:(double)arg2 ;
@end

