/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTDefaultsManager, RTPlaceInferenceManager;

@interface RTVisitLabeler : NSObject {

	RTDefaultsManager* _defaultsManager;
	RTPlaceInferenceManager* _placeInferenceManager;

}

@property (nonatomic,readonly) RTDefaultsManager * defaultsManager;                          //@synthesize defaultsManager=_defaultsManager - In the implementation block
@property (nonatomic,readonly) RTPlaceInferenceManager * placeInferenceManager;              //@synthesize placeInferenceManager=_placeInferenceManager - In the implementation block
-(id)init;
-(RTDefaultsManager *)defaultsManager;
-(RTPlaceInferenceManager *)placeInferenceManager;
-(id)initWithDefaultsManager:(id)arg1 placeInferenceManager:(id)arg2 ;
-(void)labelVisit:(id)arg1 handler:(/*^block*/id)arg2 ;
-(char)labelVisit:(id)arg1 error:(id*)arg2 ;
@end

