/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTVisitLocationPoints, RTVisit;

@interface RTVisitCluster : NSObject {

	RTVisitLocationPoints* _points;
	RTVisit* _visit;

}

@property (nonatomic,readonly) RTVisitLocationPoints * points;              //@synthesize points=_points - In the implementation block
@property (nonatomic,readonly) RTVisit * visit;                             //@synthesize visit=_visit - In the implementation block
-(id)description;
-(id)init;
-(RTVisitLocationPoints *)points;
-(RTVisit *)visit;
-(id)initWithPoints:(id)arg1 visit:(id)arg2 ;
-(id)initWithPoints:(id)arg1 ;
-(char)isExitDateBeforeDate:(id)arg1 ;
-(char)isDateInside:(id)arg1 ;
-(char)isPartialAndExitDateIsEqualToDate:(id)arg1 ;
-(char)isCompleteAndExitDateIsEqualToDate:(id)arg1 ;
@end

