/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTLocation, NSArray;

@interface RTVisitLocationPoints : NSObject {

	RTLocation* _centroid;
	NSArray* _locations;

}

@property (nonatomic,readonly) NSArray * locations;                //@synthesize locations=_locations - In the implementation block
@property (nonatomic,readonly) RTLocation * centroid;              //@synthesize centroid=_centroid - In the implementation block
-(id)description;
-(id)init;
-(double)duration;
-(NSArray *)locations;
-(id)initWithLocations:(id)arg1 ;
-(RTLocation *)centroid;
-(id)lastDate;
-(id)firstDate;
-(void)enumerateLowSpeedSegementsUsingBlock:(id)arg1 block:(/*^block*/id)arg2 ;
@end

