/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:15 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libsysmon.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libsysmon.dylib/OS_sysmon_object.h>
#import <libobjc.A.dylib/OS_sysmon_request.h>

@protocol OS_sysmon_request <OS_sysmon_object>
@end


@class NSString;

@interface OS_sysmon_request : OS_sysmon_object <OS_sysmon_request>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(oneway void)release;
-(void)dealloc;
@end

