/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:52:16 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libIASUnifiedProgress.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IASPRegistryManager : NSObject
+(void)clear;
+(id)currentPhaseName;
+(void)setCurrentPhaseName:(id)arg1 ;
+(id)phases;
+(void)setPhases:(id)arg1 ;
+(float)startingPercentage;
@end

