/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:02 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_nw_interface, OS_nw_path_flow_registration, OS_nw_path_flow;
@class NSObject;

@interface nw_interpose_flow : NSObject {

	NSObject*<OS_nw_interface> _interface;
	NSObject*<OS_nw_path_flow_registration> _registration;
	NSObject*<OS_nw_path_flow> _flow;
	/*^block*/id _eventHandler;

}
-(void)dealloc;
-(void)close;
-(id)initWithInterface:(id)arg1 registration:(id)arg2 eventHandler:(/*^block*/id)arg3 ;
-(void)notifyFlowEvent:(int)arg1 ;
-(void)closeFlow;
-(void)clearFlowEventHandler;
-(void)resetFlow:(id)arg1 ;
-(char)matchNexusAgent:(unsigned char)arg1 ;
-(char)matchNexusAgentWithFlow:(id)arg1 ;
-(char)matchNexusInstance:(id)arg1 ;
@end

