/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:02 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnetwork.dylib/NWConcrete_nw_endpoint.h>

@protocol OS_nw_txt_record, OS_dispatch_data;
@class NSObject;

@interface NWOSHostEndpoint : NWConcrete_nw_endpoint {

	char* hostname;
	unsigned short port;
	unsigned short priority;
	unsigned short weight;
	NSObject*<OS_nw_txt_record> txt_record;
	NSObject*<OS_dispatch_data> ech_config;

}
-(void)dealloc;
-(id)copyDictionary;
-(unsigned)type;
-(unsigned short)port;
-(unsigned short)weight;
-(void)setWeight:(unsigned short)arg1 ;
-(void)setPriority:(unsigned short)arg1 ;
-(unsigned short)priority;
-(char*)createDescription:(BOOL)arg1 ;
-(char)isEqualToEndpoint:(id)arg1 matchInterface:(BOOL)arg2 matchParent:(BOOL)arg3 ;
-(id)copyEndpoint;
-(unsigned long long)getHash;
-(const char*)hostname;
-(const char*)domainForPolicy;
-(id)txtRecord;
-(void)setTxtRecord:(id)arg1 ;
-(id)echConfig;
-(void)setEchConfig:(id)arg1 ;
@end

